<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>GW2EIParserAvalonia</RootNamespace>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationIcon>Content\ArenaNet\LI.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <Deterministic>false</Deterministic>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AssemblyName>GuildWars2EliteInsights</AssemblyName>
        <OutputPath>..\..\..\GW2EI.bin\$(Configuration)\UI\all\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
        <Configurations>Debug;Release;Release-Win;Release-Linux;Release-MacOS;Release-MacOS-Arm</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release-Linux'">
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release-Win'">
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release-MacOS'">
        <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release-MacOS-Arm'">
        <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release-MacOS-Arm' or '$(Configuration)' == 'Release-MacOS' Or '$(Configuration)' == 'Release-Win' Or '$(Configuration)' == 'Release-Linux'">
        <OutputPath>..\..\..\GW2EI.bin\Release\UI\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoRewards|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU' or '$(Configuration)|$(Platform)'=='Release-Win|AnyCPU' or '$(Configuration)|$(Platform)'=='Release-Linux|AnyCPU' or '$(Configuration)|$(Platform)'=='Release-MacOS|AnyCPU' or '$(Configuration)|$(Platform)'=='Release-MacOS-Arm|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Trace|AnyCPU'">
        <DebugType>none</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DefineConstants>TRACING</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
        <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
        <DefineConstants>$(DefineConstants);MACOS</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
        <DefineConstants>$(DefineConstants);MACOS-ARM</DefineConstants>
    </PropertyGroup>

    <Target Name="RemovePdbFilesFromOutput" AfterTargets="CopyFilesToOutputDirectory" Condition="'$(Configuration)' == 'Release' Or '$(Configuration)' == 'Release-Win' Or '$(Configuration)' == 'Release-Linux' Or '$(Configuration)' == 'Release-MacOS' Or '$(Configuration)' == 'Release-MacOS-Arm'">
        <ItemGroup>
            <PdbFilesToDelete Include="$(TargetDir)**/*.pdb" />
        </ItemGroup>
        <Delete Files="@(PdbFilesToDelete)" />
    </Target>

    <PropertyGroup>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <Authors>EliphasNUIT, Linkaaaa</Authors>
        <RepositoryUrl>https://github.com/baaron4/GW2-Elite-Insights-Parser</RepositoryUrl>
        <PackageId>GuildWars2EliteInsights.GW2EIParser</PackageId>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Content\ArenaNet\LI.ico" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\GW2EI.Library\GW2EI.Services\GW2EIParserCommons\GW2EIParserCommons.csproj" />
        <ProjectReference Include="..\..\..\GW2EI.Library\GW2EI.Repositories\GW2EIGW2API\GW2EIGW2API.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\UpdaterWindow.axaml.cs">
            <DependentUpon>UpdaterWindow.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\SettingsWindow.axaml.cs">
            <DependentUpon>SettingsWindow.axaml</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
