<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Configurations>Debug;Release;NoRewards;Trace</Configurations>
        <Version>0.83.0</Version>
        <IsPackable>true</IsPackable>
        <PackageId>GuildWars2EliteInsights.GW2EIBuilders</PackageId>
        <Company>GW2 Elite Insights</Company>
        <Product>GW2 Elite Insights</Product>
        <Authors>EliphasNUIT</Authors>
        <Description>Generates HTML reports and JSON for parsed evtc files</Description>
        <RepositoryUrl>https://github.com/baaron4/GW2-Elite-Insights-Parser</RepositoryUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Trace|AnyCPU'">
        <DefineConstants>TRACING</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoRewards|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <None Include="Resources\**\*.css" />
        <None Include="Resources\**\*.js" />
        <None Include="Resources\**\*.html" />
    </ItemGroup>

    <PropertyGroup>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <UserSecretsId>deaea9ef-69e9-4b48-ba82-b2294277674f</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GW2EIEvtcParser\GW2EIEvtcParser.csproj" />
        <ProjectReference Include="..\..\GW2EI.Models\GW2EIJSON\GW2EIJSON.csproj" />
        <ProjectReference Include="..\..\GW2EI.Repositories\GW2EIGW2API\GW2EIGW2API.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

</Project>
