<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <Configurations>Debug;Release;NoRewards;Trace</Configurations>
        <DebugSymbols>true</DebugSymbols>
        <Version>4.0.2</Version>
        <PackageId>GuildWars2EliteInsights.GW2EIDiscord</PackageId>
        <Product>GW2 Elite Insights</Product>
        <Company>GW2 Elite Insights</Company>
        <Authors>EliphasNUIT</Authors>
        <RepositoryUrl>https://github.com/baaron4/GW2-Elite-Insights-Parser</RepositoryUrl>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Trace|AnyCPU'">
        <DefineConstants>TRACING</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='NoRewards|AnyCPU'">
        <DefineConstants>DEBUG</DefineConstants>
    </PropertyGroup>

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    
    <PropertyGroup>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Discord.Net.Webhook" Version="3.11.0" />
    </ItemGroup>

</Project>
