using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;

namespace GW2EIJSON
{
    /// <summary>
    /// Class representing buff on targets
    /// </summary>
    public class JsonBuffsUptime
    {
        /// <summary>
        /// Target buff item
        /// </summary>
        public class JsonBuffsUptimeData
        {
            [JsonProperty]
            /// <summary>
            /// Uptime of the buff
            /// </summary>
            public double Uptime { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Presence of the buff (intensity only)
            /// </summary>
            public double Presence { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff generated by
            /// </summary>
            public IReadOnlyDictionary<string, double> Generated { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff overstacked by
            /// </summary>
            public IReadOnlyDictionary<string, double> Overstacked { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff wasted by
            /// </summary>
            public IReadOnlyDictionary<string, double> Wasted { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff extended by unknown for
            /// </summary>
            public IReadOnlyDictionary<string, double> UnknownExtended { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff by extension
            /// </summary>
            public IReadOnlyDictionary<string, double> ByExtension { get; internal set; }
            [JsonProperty]
            /// <summary>
            /// Buff extended for
            /// </summary>
            public IReadOnlyDictionary<string, double> Extended { get; internal set; }

            [JsonConstructor]
            internal JsonBuffsUptimeData()
            {

            }      
        }

        [JsonProperty]
        /// <summary>
        /// ID of the buff
        /// </summary>
        /// <seealso cref="JsonLog.BuffMap"/>
        public long Id { get; internal set; }
        [JsonProperty]
        /// <summary>
        /// Array of buff data \n
        /// Length == # of phases
        /// </summary>
        /// <seealso cref="JsonBuffsUptimeData"/>
        public IReadOnlyList<JsonBuffsUptimeData> BuffData { get; internal set; }
        [JsonProperty]
        /// <summary>
        /// Array of int[2] that represents the number of buff \n
        /// Array[i][0] will be the time, Array[i][1] will be the number of buff present from Array[i][0] to Array[i+1][0] \n
        /// If i corresponds to the last element that means the status did not change for the remainder of the fight
        /// </summary>
        public IReadOnlyList<IReadOnlyList<int>> States { get; internal set; }

        [JsonConstructor]
        internal JsonBuffsUptime()
        {

        }     
    }

}
