using System.Collections.Generic;
using GW2EIEvtcParser.EIData.Buffs;
using static GW2EIEvtcParser.ArcDPSEnums;
using static GW2EIEvtcParser.EIData.Buff;
using static GW2EIEvtcParser.ParserHelper;
using static GW2EIEvtcParser.SkillIDs;

namespace GW2EIEvtcParser.EIData
{
    internal static class EncounterBuffs
    {


        internal static readonly List<Buff> FractalInstabilities = new List<Buff>()
        {
            // Legacy
            new Buff("Mistlock Instability: Fleeting Precision", MistlockInstabilityFleetingPrecision, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Impaired Immunity", MistlockInstabilityImpairedImmunity, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Losing Control", MistlockInstabilityLosingControl, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Mist Stalker", MistlockInstabilityMistStalker, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Slippery Slope 1", MistlockInstabilitySlipperySlope1, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilitySlipperySlope),
            new Buff("Mistlock Instability: Slippery Slope 2", MistlockInstabilitySlipperySlope2, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilitySlipperySlope),
            new Buff("Mistlock Instability: Stormy Weather", MistlockInstabilityStormyWeather, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Birds", MistlockInstabilityBirds, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityBirds),
            new Buff("Mistlock Instability: Tainted Renewal", MistlockInstabilityTaintedRenewal, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Stamina", MistlockInstabilityStamina, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Playing Favorites", MistlockInstabilityPlayingFavorites, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Overextended", MistlockInstabilityOverextended, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Keep Them in Line", MistlockInstabilityKeepTheminLine, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Ill and Chill", MistlockInstabilityIllAndChill, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Frosty", MistlockInstabilityFrosty, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Bloodlust", MistlockInstabilityBloodlust, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Antielitism", MistlockInstabilityAntielitism, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            new Buff("Mistlock Instability: Agonizing Expedition", MistlockInstabilityAgonizingExpedition, Source.FractalInstability, BuffClassification.Other, BuffImages.Instability),
            // Current
            new Buff("Mistlock Instability: Adrenaline Rush", MistlockInstabilityAdrenalineRush, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityAdrenalineRush),
            new Buff("Mistlock Instability: Afflicted", MistlockInstabilityAfflicted, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityAfflicted),
            new Buff("Mistlock Instability: Boon Overload", MistlockInstabilityBoonOverload, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityBoonOverload),
            new Buff("Mistlock Instability: Flux Bomb", MistlockInstabilityFluxBomb, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityFluxBomb),
            new Buff("Mistlock Instability: Fractal Vindicators", MistlockInstabilityFractalVindicators, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityFractalVindicator),
            new Buff("Mistlock Instability: Frailty", MistlockInstabilityFrailty, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityFrailty),
            new Buff("Mistlock Instability: Hamstrung", MistlockInstabilityHamstrung, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityHamstrung),
            new Buff("Mistlock Instability: Last Laugh", MistlockInstabilityLastLaugh, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityLastLaugh),
            new Buff("Mistlock Instability: Mists Convergence", MistlockInstabilityMistsConvergence, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityMistsConvergence),
            new Buff("Mistlock Instability: No Pain, No Gain", MistlockInstabilityNoPainNoGain, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityNoPainNoGain),
            new Buff("Mistlock Instability: Outflanked", MistlockInstabilityOutflanked, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityOutflanked),
            new Buff("Mistlock Instability: Social Awkwardness", MistlockInstabilitySocialAwkwardness, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilitySocialAwkwardness),
            new Buff("Mistlock Instability: Stick Together", MistlockInstabilityStickTogether, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityStickTogether),
            new Buff("Mistlock Instability: Sugar Rush", MistlockInstabilitySugarRush, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilitySugarRush),
            new Buff("Mistlock Instability: Toxic Trail", MistlockInstabilityToxicTrail, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityToxicTrail),
            new Buff("Mistlock Instability: Vengeance", MistlockInstabilityVengeance, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityVengeance),
            new Buff("Mistlock Instability: We Bleed Fire", MistlockInstabilityWeBleedFire, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityWeBleedFire),
            new Buff("Mistlock Instability: Toxic Sickness", MistlockInstabilityToxicSickness, Source.FractalInstability, BuffClassification.Other, BuffImages.InstabilityToxicSickness),
        };

        internal static readonly List<Buff> FightSpecific = new List<Buff>
        {
            // Generic
            new Buff("Emboldened", Emboldened, Source.FightSpecific,BuffStackType.Stacking, 5, BuffClassification.Offensive, BuffImages.Emboldened),
            new Buff("Spectral Agony", SpectralAgony, Source.FightSpecific,BuffStackType.Stacking, 25, BuffClassification.Debuff, BuffImages.SpectralAgony),
            new Buff("Enraged (?)", Enraged1_Unknown, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged (??)", Enraged2_Unknown, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 1 (100%)", Enraged_100_strike, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 2 (100%)", Enraged_100_strike_25_reduc, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 1 (200%)", Enraged_200_strike, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 2 (200%)", Enraged_200, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 3 (200%)", Enraged3_200, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged 4 (200%)", Enraged_200_strike_50_reduc, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged (300%)", Enraged_300_strike_75_reduc, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged (500%)", Enraged_500, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Call of the Mists", CallOfTheMists, Source.FightSpecific, BuffClassification.Other, BuffImages.CallOfTheMists),
            new Buff("Untargetable", Untargetable, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined ),
            // Strike Essences
            new Buff("Essence of Vigilance Tier 1", EssenceOfVigilanceTier1, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfVigilance),
            new Buff("Essence of Vigilance Tier 2", EssenceOfVigilanceTier2, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfVigilance),
            new Buff("Essence of Vigilance Tier 3", EssenceOfVigilanceTier3, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfVigilance),
            new Buff("Essence of Vigilance Tier 4", EssenceOfVigilanceTier4, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfVigilance),
            new Buff("Power of Vigilance Tier 1", PowerOfVigilanceTier1, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfVigilance),
            new Buff("Power of Vigilance Tier 2", PowerOfVigilanceTier2, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfVigilance),
            new Buff("Power of Vigilance Tier 3", PowerOfVigilanceTier3, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfVigilance),
            new Buff("Power of Vigilance Tier 4", PowerOfVigilanceTier4, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfVigilance),
            new Buff("Essence of Resilience Tier 1", EssenceOfResilienceTier1, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfResilience),
            new Buff("Essence of Resilience Tier 2", EssenceOfResilienceTier2, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfResilience),
            new Buff("Essence of Resilience Tier 3", EssenceOfResilienceTier3, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfResilience),
            new Buff("Essence of Resilience Tier 4", EssenceOfResilienceTier4, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfResilience),
            new Buff("Power of Resilience Tier 1", PowerOfResilienceTier1, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfResilience),
            new Buff("Power of Resilience Tier 2", PowerOfResilienceTier2, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfResilience),
            new Buff("Power of Resilience Tier 3", PowerOfResilienceTier3, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfResilience),
            new Buff("Power of Resilience Tier 4", PowerOfResilienceTier4, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfResilience),
            new Buff("Essence of Valor Tier 1", EssenceOfValorTier1, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfValor),
            new Buff("Essence of Valor Tier 2", EssenceOfValorTier2, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfValor),
            new Buff("Essence of Valor Tier 3", EssenceOfValorTier3, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfValor),
            new Buff("Essence of Valor Tier 4", EssenceOfValorTier4, Source.FightSpecific,BuffStackType.StackingConditionalLoss, 30, BuffClassification.Other, BuffImages.EssenceOfValor),
            new Buff("Power of Valor Tier 1", PowerOfValorTier1, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfValor),
            new Buff("Power of Valor Tier 2", PowerOfValorTier2, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfValor),
            new Buff("Power of Valor Tier 3", PowerOfValorTier3, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfValor),
            new Buff("Power of Valor Tier 4", PowerOfValorTier4, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfValor),
            // Unknown Fixation            
            new Buff("Fixated 1(???)", Fixated1, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated 2(???)", Fixated2, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            //////////////////////////////////////////////
            // Mordremoth
            new Buff("Parietal Mastery", ParietalMastery, Source.FightSpecific, BuffClassification.Other, BuffImages.ParietalMastery),
            new Buff("Parietal Origin", ParietalOrigin, Source.FightSpecific, BuffClassification.Other, BuffImages.ParietalMastery),
            new Buff("Temporal Mastery", TemporalMastery, Source.FightSpecific, BuffClassification.Other, BuffImages.TemporalMastery),
            new Buff("Temporal Origin", TemporalOrigin, Source.FightSpecific, BuffClassification.Other, BuffImages.TemporalMastery),
            new Buff("Occipital Mastery", OccipitalMastery, Source.FightSpecific, BuffClassification.Other, BuffImages.OccipitalMastery),
            new Buff("Occipital Origin", OccipitalOrigin, Source.FightSpecific, BuffClassification.Other, BuffImages.OccipitalMastery),
            new Buff("Frontal Mastery", FrontalMastery, Source.FightSpecific, BuffClassification.Other, BuffImages.FrontalMastery),
            new Buff("Frontal Origin", FrontalOrigin, Source.FightSpecific, BuffClassification.Other, BuffImages.FrontalMastery),
            new Buff("Exposed (Mordremoth)", ExposedMordremoth, Source.Common, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Exposed),
            new Buff("Weakened (Buff 1)", WeakenedBuff1, Source.Common, BuffClassification.Other, BuffImages.Weakened),
            new Buff("Weakened (Buff 2)", WeakenedBuff2, Source.Common, BuffClassification.Other, BuffImages.Weakened),
            new Buff("Empowered (Hearts and Minds)", EmpoweredHeartsAndMinds, Source.Common, BuffClassification.Other, BuffImages.EmpoweredHeartAndMinds),
            new Buff("Power (Hearts and Minds)", PowerHeartsAndMinds, Source.Common, BuffClassification.Other, BuffImages.PowerHeartAndMinds),
            new Buff("Shifty Aura", ShiftyAura, Source.Common, BuffClassification.Other, BuffImages.BrandedAura),
            new Buff("Fiery Block", FieryBlock, Source.Common, BuffClassification.Other, BuffImages.ShieldStance),
            //////////////////////////////////////////////
            // VG
            new Buff("Blue Pylon Power", BluePylonPower, Source.FightSpecific, BuffClassification.Other, BuffImages.BluePylon),
            new Buff("Pylon Attunement: Red", PylonAttunementRed, Source.FightSpecific, BuffClassification.Other, BuffImages.RedPylon),
            new Buff("Pylon Attunement: Blue", PylonAttunementBlue, Source.FightSpecific, BuffClassification.Other, BuffImages.BluePylon),
            new Buff("Pylon Attunement: Green", PylonAttunementGreen, Source.FightSpecific, BuffClassification.Other, BuffImages.GreenPylon),
            new Buff("Unstable Pylon: Red", UnstablePylonRed, Source.FightSpecific, BuffClassification.Other, BuffImages.UnstableRed),
            new Buff("Unstable Pylon: Blue", UnstablePylonBlue, Source.FightSpecific, BuffClassification.Other, BuffImages.UnstableBlue),
            new Buff("Unstable Pylon: Green", UnstablePylonGreen, Source.FightSpecific, BuffClassification.Other, BuffImages.UnstableGreen),
            new Buff("Magic Aura", MagicAuraBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicAura),
            new Buff("Magic Aura: Red", MagicAuraRedBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicAuraRed),
            new Buff("Magic Aura: Blue", MagicAuraBlueBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicAuraBlue),
            new Buff("Magic Aura: Green", MagicAuraGreenBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicAuraGreen),
            // Gorseval
            new Buff("Spirited Fusion", SpiritedFusion, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.SpiritedFusion),
            new Buff("Protective Shadow", ProtectiveShadow, Source.FightSpecific, BuffClassification.Other, BuffImages.ProtectiveShadow),
            new Buff("Ghastly Prison", GhastlyPrison, Source.FightSpecific, BuffClassification.Debuff, BuffImages.GhastlyPrison),
            new Buff("Vivid Echo", VividEcho, Source.FightSpecific, BuffStackType.Queue, 5, BuffClassification.Other, BuffImages.VividEcho),
            new Buff("Spectral Darkness", SpectralDarkness, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.SpectralDarkness),
            // Sabetha    
            new Buff("Shell-Shocked", ShellShocked, Source.FightSpecific, BuffClassification.Other, BuffImages.ShellShocked),
            new Buff("Sapper Bomb", SapperBombBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.SapperBomb),
            new Buff("Sapper Bomb Damage", SapperBombDamageBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.SapperBomb),
            new Buff("Time Bomb", TimeBomb, Source.FightSpecific, BuffClassification.Other, BuffImages.TimeBomb),
            //////////////////////////////////////////////
            // Slothasor
            new Buff("Narcolepsy", NarcolepsyBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Nauseated", Nauseated, Source.FightSpecific, BuffClassification.Other, BuffImages.Nauseated),
            new Buff("Magic Transformation", MagicTransformation, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicTransformation),
            new Buff("Fixated (Slothasor)", FixatedSlothasor, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Volatile Poison", VolatilePoisonBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.VolatilePoison),
            new Buff("Slippery Slubling", SlipperySlubling, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Trio
            new Buff("Not the Bees!", NotTheBees, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Other, BuffImages.ThrowJar),
            new Buff("Slow Burn", SlowBurn, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.HeatWave),
            new Buff("Targeted", Targeted, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetedLocust),
            new Buff("Target!", Target, Source.FightSpecific, BuffStackType.Stacking, 20, BuffClassification.Other, BuffImages.Target),
            new Buff("Locust Trail", LocustTrail, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Target),
            new Buff("Environmentally Friendly", EnvironmentallyFriendly, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Matthias
            new Buff("Blood Shield Abo", BloodShieldAbo, Source.FightSpecific, BuffStackType.Stacking, 18, BuffClassification.Other, BuffImages.BloodShield),
            new Buff("Blood Shield", BloodShield, Source.FightSpecific, BuffStackType.Stacking, 18, BuffClassification.Other, BuffImages.BloodShield),
            new Buff("Blood Fueled (Player)", BloodFueledPlayer, Source.FightSpecific, BuffStackType.Stacking, 1, BuffClassification.Offensive, BuffImages.BloodFueled),
            new Buff("Blood Fueled (Matthias)", BloodFueledMatthias, Source.FightSpecific, BuffStackType.Stacking, 15, BuffClassification.Offensive, BuffImages.BloodFueled),
            new Buff("Unstable Blood Magic", UnstableBloodMagic, Source.FightSpecific, BuffClassification.Other, BuffImages.UnstableBloodMagic),
            new Buff("Corruption", Corruption1, Source.FightSpecific, BuffClassification.Other, BuffImages.LocustTrail),
            new Buff("Corruption 2", Corruption2, Source.FightSpecific, BuffClassification.Other, BuffImages.LocustTrail),
            new Buff("Sacrifice", MatthiasSacrifice, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Sacrifice Selection", MatthiasSacrificeSelection, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Unbalanced", Unbalanced, Source.FightSpecific, BuffClassification.Other, BuffImages.Unbalanced),
            new Buff("Zealous Benediction", ZealousBenediction, Source.FightSpecific, BuffClassification.Other, BuffImages.Unstable),
            new Buff("Snowstorm", SnowstormBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Snowstorm),
            new Buff("Heat Wave", HeatWave, Source.FightSpecific, BuffClassification.Other, BuffImages.HeatWave),
            new Buff("Downpour", DownpourBuff, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Downpour),
            new Buff("Snowstorm (Matthias)", SnowstormMatthias, Source.FightSpecific, BuffClassification.Other, BuffImages.Snowstorm),
            new Buff("Heat Wave (Matthias)", HeatWaveMatthias, Source.FightSpecific, BuffClassification.Other, BuffImages.HeatWave),
            new Buff("Downpour (Matthias)", DownpourMatthias, Source.FightSpecific, BuffClassification.Other, BuffImages.Downpour),
            new Buff("Unstable", Unstable, Source.FightSpecific, BuffClassification.Other, BuffImages.Unstable),      
            //////////////////////////////////////////////
            // Escort
            new Buff("Toxic Spores (Escort)", EscortToxicSpores, Source.FightSpecific, BuffClassification.Debuff, BuffImages.ToxicSpores),
            new Buff("Healing Cleanse (Escort)", EscortHealingCleanse, Source.FightSpecific, BuffClassification.Support, BuffImages.Elasticity),
            new Buff("Surveilled (Escort)", EscortSurveilled, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Debuff, BuffImages.Fear),
            new Buff("Achievement Eligibility: Fast Siege", AchievementEligibilityFastSiege, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Love Is Bunny", AchievementEligibilityLoveIsBunny, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Mine Control", AchievementEligibilityMineControl, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // KC
            // This achievement buff can be found during Twisted Castle and Xera too, very rare though
            new Buff("Achievement Eligibility: Down, Down, Downed", AchievementEligibilityDownDownDowned, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Compromised", Compromised, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Compromised),
            new Buff("Xera's Boon", XerasBoon, Source.FightSpecific, BuffClassification.Other, BuffImages.XerasBoon),
            new Buff("Xera's Fury", XerasFury, Source.FightSpecific, BuffClassification.Other, BuffImages.XerasFury),
            new Buff("Statue Fixated", StatueFixated1, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Statue Fixated 2", StatueFixated2, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Incoming!", Incoming, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Crimson Attunement (Orb)", CrimsonAttunementOrb, Source.FightSpecific, BuffClassification.Other, BuffImages.CrimsonAttunement),
            new Buff("Radiant Attunement (Orb)", RadiantAttunementOrb, Source.FightSpecific, BuffClassification.Other, BuffImages.RadiantAttunement),
            new Buff("Crimson Attunement (Phantasm)", CrimsonAttunementPhantasm, Source.FightSpecific, BuffClassification.Other, BuffImages.CrimsonAttunement),
            new Buff("Radiant Attunement (Phantasm)", RadiantAttunementPhantasm, Source.FightSpecific, BuffClassification.Other, BuffImages.RadiantAttunement),
            new Buff("Magic Blast", MagicBlast, Source.FightSpecific, BuffStackType.Stacking, 35, BuffClassification.Other, BuffImages.MagicBlast),
            new Buff("Gaining Power", GainingPower, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Unbreakable", Unbreakable, Source.FightSpecific, BuffStackType.Stacking, 2, BuffClassification.Other, BuffImages.XerasEmbrace),
            new Buff("Spatial Denial", SpatialDenial, Source.FightSpecific, BuffClassification.Other, BuffImages.PhantasmalWarlock),
            // Twisted Castle
            new Buff("Spatial Distortion", SpatialDistortion, Source.FightSpecific, BuffClassification.Other, BuffImages.BloodstoneBlessed),
            new Buff("Madness", Madness, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Debuff, BuffImages.Madness),
            new Buff("Still Waters", StillWaters, Source.FightSpecific, BuffClassification.Other, BuffImages.StillWaters),
            new Buff("Soothing Waters", SoothingWaters, Source.FightSpecific, BuffClassification.Other, BuffImages.SoothingWaters),
            new Buff("Chaotic Haze", ChaoticHaze, Source.FightSpecific, BuffClassification.Other, BuffImages.LavaFont),
            new Buff("Creeping Pursuit", CreepingPursuit, Source.FightSpecific, BuffClassification.Other, BuffImages.CreepingPursuit),
            new Buff("Achievement Eligibility: Evasive Maneuver", AchievementEligibilityEvasiveManeuver, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Mildly Insane", AchievementEligibilityMildlyInsane, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Xera      
            new Buff("Derangement", Derangement, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Debuff, BuffImages.Derangement),
            new Buff("Bending Chaos", BendingChaos, Source.FightSpecific, BuffStackType.Stacking, 11, BuffClassification.Other, BuffImages.Target2),
            new Buff("Shifting Chaos", ShiftingChaos, Source.FightSpecific, BuffStackType.Stacking, 11, BuffClassification.Other, BuffImages.ShiftingChaos),
            new Buff("Twisting Chaos", TwistingChaos, Source.FightSpecific, BuffStackType.Stacking, 11, BuffClassification.Other, BuffImages.TwistingChaos),
            new Buff("Intervention (SAK)", InterventionSkillOwnerBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Intervention),
            new Buff("Intervention (Invuln)", InterventionInvulnerabilityBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Intervention),
            new Buff("Bloodstone Protection", BloodstoneProtection, Source.FightSpecific, BuffClassification.Other, BuffImages.BloodstoneProtection),
            new Buff("Bloodstone Blessed", BloodstoneBlessed, Source.FightSpecific, BuffClassification.Other, BuffImages.BloodstoneBlessed),
            new Buff("Void Zone", VoidZone, Source.FightSpecific, BuffClassification.Other, BuffImages.VoidZone),
            new Buff("Gravity Well (Xera)", GravityWellXera, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Hero's Departure", HerosDeparture, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Hero's Return", HerosReturn, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            //////////////////////////////////////////////
            // Cairn
            new Buff("Shared Agony", SharedAgony, Source.FightSpecific, BuffClassification.Debuff, BuffImages.SharedAgony),
            new Buff("Enraged (Cairn)", EnragedCairn, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged (Cairn 2)", EnragedCairn2, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Unseen Burden", UnseenBurden, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Debuff, BuffImages.UnseenBurden),
            new Buff("Countdown", Countdown, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Countdown),
            new Buff("Gaze Avoidance", GazeAvoidance, Source.FightSpecific, BuffClassification.Other, BuffImages.GazeAvoidance),
            new Buff("Celestial Dash", CelestialDashBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.CelestialDash),
            // Mursaat Overseer
            new Buff("Empowered (MO)", EmpoweredMO, Source.FightSpecific, BuffStackType.Stacking, 4, BuffClassification.Other, BuffImages.Empowered),
            new Buff("Mursaat Overseer's Shield", MursaatOverseersShield, Source.FightSpecific, BuffClassification.Other, BuffImages.Dispel),
            new Buff("Protect", ProtectBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Protect),
            new Buff("Dispel", DispelBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Dispel),
            new Buff("Claim", ClaimBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Claim),
            // Samarog
            new Buff("Fixated (Samarog)", FixatedSamarog, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Classic Misdirection", ClassicMisdirection, Source.FightSpecific, BuffClassification.Other, BuffImages.TearInstability),
            new Buff("Fixated (Guldhem)", FixatedGuldhem, Source.FightSpecific, BuffClassification.Other, BuffImages.FixateGuldhem),
            new Buff("Strengthened Bond: Guldhem", StrengthenedBondGuldhem, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.StrengthenedBondGuldhem),
            new Buff("Fixated (Rigom)", FixatedRigom, Source.FightSpecific, BuffClassification.Other, BuffImages.FixateRigom),
            new Buff("Strengthened Bond: Rigom", StrengthenedBondRigom, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.StrengthenedBondRigom),
            new Buff("Inevitable Betrayal (Big)", InevitableBetrayalBig, Source.FightSpecific, BuffClassification.Other, BuffImages.FeedingFrenzy),
            new Buff("Inevitable Betrayal (Small)", InevitableBetrayalSmall, Source.FightSpecific, BuffClassification.Other, BuffImages.FeedingFrenzy),
            new Buff("Soul Swarm", SoulSwarm, Source.FightSpecific, BuffClassification.Other, BuffImages.SoulSwarm),
            new Buff("Fanatical Resilience", FanaticalResilience, Source.FightSpecific, BuffClassification.Other, BuffImages.Burrowed),
            new Buff("Brutalized", BrutalizeBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Burrowed),
            // Deimos
            new Buff("Unnatural Signet", UnnaturalSignet, Source.FightSpecific, BuffClassification.Other, BuffImages.UnnaturalSignet),
            new Buff("Weak Minded", WeakMinded, Source.FightSpecific, BuffClassification.Debuff, BuffImages.UnseenBurdenDeimos),
            new Buff("Tear Instability", TearInstability, Source.FightSpecific, BuffClassification.Other, BuffImages.TearInstability),
            new Buff("Form Up and Advance!", FormUpAndAdvance, Source.FightSpecific, BuffClassification.Other, BuffImages.FormUpAndAdvance),
            new Buff("Devour", Devour, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.Devour),
            new Buff("Unseen Burden (Deimos)", UnseenBurdenDeimos, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.UnseenBurdenDeimos),
            new Buff("Green Selection", DeimosSelectedByGreen, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            //////////////////////////////////////////////
            // Soulless Horror
            new Buff("Exile's Embrace", ExilesEmbrace, Source.FightSpecific, BuffClassification.Other, BuffImages.ExilesEmbrace),
            new Buff("Fixated (SH)", FixatedSH, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Necrosis", Necrosis, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Debuff, BuffImages.Ichor),
            new Buff("Achievement Eligibility: Necro Dancer", AchievementEligibilityNecroDancer, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // River
            // This achievement buff can be found during River and every statue encounter
            new Buff("Achievement Eligibility: Statues of Limitation", AchievementEligibilityStatuesOfLimitation, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Soul Siphon", SoulSiphon, Source.FightSpecific, BuffClassification.Debuff, BuffImages.SoulSiphon),
            new Buff("Desmina's Protection", DesminasProtection, Source.FightSpecific, BuffClassification.Other, BuffImages.DesminasProtection),
            new Buff("Follower's Asylum", FollowersAsylum, Source.FightSpecific, BuffClassification.Other, BuffImages.DesminasProtection),
            new Buff("Spirit Form", SpiritForm, Source.FightSpecific, BuffClassification.Other, BuffImages.SpiritForm),
            new Buff("Mortal Coil (River)", MortalCoilRiver, Source.FightSpecific, BuffStackType.Stacking, 30, BuffClassification.Other, BuffImages.InternalCoil),
            new Buff("Energy Threshold (River)", EnergyThresholdRiver, Source.FightSpecific, BuffStackType.Stacking, 5, BuffClassification.Other, BuffImages.SpiritForm),
            // Broken King          
            new Buff("Frozen Wind", FrozenWind, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Debuff, BuffImages.FrozenWind),
            new Buff("Shield of Ice", ShieldOfIce, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 99, BuffClassification.Other, BuffImages.ShieldOfIce),
            new Buff("Glaciate", Glaciate, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Glaciate),
            // Eater of Soul         
            new Buff("Soul Digestion", SoulDigestion, Source.FightSpecific, BuffClassification.Other, BuffImages.SoulDigestion),
            new Buff("Reclaimed Energy", ReclaimedEnergyBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.ReclaimedEnergy),
            new Buff("Mortal Coil (Statue of Death)", MortalCoilStatueOfDeath, Source.FightSpecific, BuffStackType.Stacking, 30, BuffClassification.Other, BuffImages.MortalCoil),
            new Buff("Empowered (Statue of Death)", EmpoweredStatueOfDeath, Source.FightSpecific, BuffClassification.Offensive, BuffImages.EmpoweredEater),
            // Eyes
            new Buff("Last Grasp (Judgment)", LastGraspJudgment, Source.FightSpecific, BuffClassification.Other, BuffImages.LastGrasp),
            new Buff("Last Grasp (Fate)", LastGraspFate, Source.FightSpecific, BuffClassification.Other, BuffImages.LastGrasp),
            new Buff("Exposed (Statue of Darkness)", ExposedStatueOfDarkness, Source.FightSpecific, BuffClassification.Other, BuffImages.ExposedEyes),
            new Buff("Light Carrier", LightCarrier, Source.FightSpecific, BuffClassification.Other, BuffImages.TorchFielder),
            new Buff("Empowered (Light Thief)", EmpoweredLightThief, Source.FightSpecific, BuffClassification.Other, BuffImages.SoulDigestion),
            // Dhuum
            new Buff("Mortal Coil (Dhuum)", MortalCoilDhuum, Source.FightSpecific, BuffStackType.Stacking, 30, BuffClassification.Other, BuffImages.Compromised),
            new Buff("Fractured Spirit", FracturedSpirit, Source.FightSpecific, BuffClassification.Other, BuffImages.FracturedSpirit),
            new Buff("Residual Affliction", ResidualAffliction, Source.FightSpecific, BuffClassification.Other, BuffImages.ResidualAffliction),
            new Buff("Arcing Affliction", ArcingAffliction, Source.FightSpecific, BuffClassification.Other, BuffImages.ArcingAffliction),
            new Buff("One-Track Mind", OneTrackMind, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Tracked),
            new Buff("Imminent Demise", ImminentDemise, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.SuperheatedMetal),
            new Buff("Lethal Report", LethalReport, Source.FightSpecific, BuffClassification.Other, BuffImages.MantraOfSignets),
            new Buff("Hastened Demise", HastenedDemise, Source.FightSpecific, BuffClassification.Other, BuffImages.HastenedDemise),
            new Buff("Echo's Pick up", EchosPickup, Source.FightSpecific, BuffClassification.Other, BuffImages.Unstable),
            new Buff("Energy Threshold", EnergyThreshold, Source.FightSpecific, BuffStackType.Stacking, 5, BuffClassification.Other, BuffImages.SpiritForm), // Dhuum & Eater of Souls
            new Buff("Source: Pure Oblivion", SourcePureOblivionBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.CounterMagicSkill),
            new Buff("Messenger Fixation", DhuumsMessengerFixationBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Player to Soul Split Buff", DhuumPlayerToSoulTrackBuff, Source.FightSpecific, BuffClassification.Hidden, BuffImages.Unknown),
            //////////////////////////////////////////////
            // CA
            new Buff("Greatsword Power", GreatswordPower, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.GreatswordPower),
            new Buff("Fractured - Enemy", FracturedEnemy, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.BrandedAura),
            new Buff("Fractured - Allied", FracturedAllied, Source.FightSpecific, BuffStackType.Stacking, 2, BuffClassification.Debuff, BuffImages.BrandedAura),
            new Buff("Conjured Shield", ConjuredShield, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.ConjuredShield),
            new Buff("Conjured Protection", ConjuredProtection, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.InfusedShield),
            new Buff("Shielded (CA)", ShieldedCA, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.PoweredShielding),
            new Buff("Augmented Power", AugmentedPower, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.PoweredShielding),
            new Buff("Locked On", LockedOn, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Target2),
            new Buff("CA Invul", CAInvul, Source.FightSpecific, BuffClassification.Other, BuffImages.BloodFueled),
            new Buff("Arm Up", ArmUp, Source.FightSpecific, BuffClassification.Other, BuffImages.BloodFueled),
            new Buff("Fixation", Fixation, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Achievement Eligibility: Stacking Swords and Shields", AchievementEligibilityStackingSwordsAndShields, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Twin Largos
            new Buff("Aquatic Detainment", AquaticDetainmentBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Tidal Pool", TidalPoolBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Aquatic Aura (Kenut)", AquaticAuraKenut, Source.FightSpecific, BuffStackType.Stacking, 80, BuffClassification.Debuff, BuffImages.ExposeWeakness),
            new Buff("Aquatic Aura (Nikare)", AquaticAuraNikare, Source.FightSpecific, BuffStackType.Stacking, 80, BuffClassification.Debuff, BuffImages.Fractured),
            new Buff("Waterlogged", Waterlogged, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.Waterlogged),
            new Buff("Enraged (Twin Largos)", EnragedTwinLargos, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Achievement Eligibility: Don't Go in the Water", AchievementEligibilityDontGoInTheWater, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Qadim
            new Buff("Flame Armor", FlameArmor, Source.FightSpecific, BuffClassification.Other, BuffImages.MagmaOrb),
            new Buff("Qadim Invulnerable", QadimInvulnerable, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Fiery Surge", FierySurge, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.FierySurge),
            new Buff("Power of the Lamp", PowerOfTheLamp, Source.FightSpecific, BuffClassification.Other, BuffImages.BreakOut),
            new Buff("Unbearable Flames", UnbearableFlames, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 25, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Parry", Parry, Source.FightSpecific, BuffClassification.Other, BuffImages.Parry),
            new Buff("Mythwright Surge", MythwrightSurge, Source.FightSpecific, BuffClassification.Other, BuffImages.SwiftnessEffect),
            new Buff("Lamp Bond", LampBond, Source.FightSpecific, BuffClassification.Other, BuffImages.LampBond),
            new Buff("Enraged (Wyvern)", EnragedWyvern, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Enraged (Qadim)", EnragedQadim, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Resistance (Lava Elemental)", ResistanceLavaElemental, Source.FightSpecific, BuffStackType.Queue, 5, BuffClassification.Other, BuffImages.FireShield),
            new Buff("Shielded (Lava Elemental)", ShieldedLavaElemental, Source.FightSpecific, BuffClassification.Other, BuffImages.FireShield),
            new Buff("Achievement Eligibility: Manipulate the Manipulator", AchievementEligibilityManipulateTheManipulator, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Taking Turns", AchievementEligibilityTakingTurns, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            //////////////////////////////////////////////
            // Adina
            new Buff("Pillar Pandemonium", PillarPandemonium, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.CaptainsInspiration),
            new Buff("Radiant Blindness", RadiantBlindness, Source.FightSpecific, BuffStackType.Queue, 25, BuffClassification.Debuff, BuffImages.PersistentlyBlinded),
            new Buff("Diamond Palisade (Damage)", DiamondPalisadeDamage, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Diamond Palisade", DiamondPalisade, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Eroding Curse", ErodingCurse, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.ToxicGas),
            new Buff("Achievement Eligibility: Conserve the Land", AchievementEligibilityConserveTheLand, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Sabir
            new Buff("Ion Shield", IonShield, Source.FightSpecific, BuffStackType.Stacking, 80, BuffClassification.Other, BuffImages.IonShield),
            new Buff("Violent Currents", ViolentCurrents, Source.FightSpecific, BuffStackType.Stacking, 5, BuffClassification.Offensive, BuffImages.ViolentCurrents),
            new Buff("Repulsion Field", RepulsionField, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetedLocust),
            new Buff("Electrical Repulsion", ElectricalRepulsion, Source.FightSpecific, BuffClassification.Other, BuffImages.XerasFury),
            new Buff("Electro-Repulsion", ElectroRepulsion, Source.FightSpecific, BuffClassification.Other, BuffImages.ExposedEyes),
            new Buff("Eye of the Storm", EyeOfTheStorm, Source.FightSpecific, BuffClassification.Other, BuffImages.MendingWaters),
            new Buff("Bolt Break", BoltBreak, Source.FightSpecific, BuffClassification.Other, BuffImages.ViolentCurrents),
            new Buff("Achievement Eligibility: Charged Winds", AchievementEligibilityChargedWinds, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Peerless Qadim
            new Buff("Erratic Energy", ErraticEnergy, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Unstable),
            new Buff("Power Share", PowerShare, Source.FightSpecific, BuffStackType.Stacking, 3, BuffClassification.Other, BuffImages.PowerShare),
            new Buff("Sapping Surge", SappingSurge, Source.FightSpecific, BuffClassification.Debuff, BuffImages.GuiltExploitation),
            new Buff("Chaos Corrosion", ChaosCorrosion, Source.FightSpecific, BuffClassification.Other, BuffImages.Fractured),
            new Buff("Fixated (Qadim the Peerless)", FixatedQadimThePeerless, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Magma Drop", MagmaDrop, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetedLocust),
            new Buff("Critical Mass", CriticalMass, Source.FightSpecific, BuffClassification.Other, BuffImages.OrbOfAscension),
            new Buff("Kinetic Abundance", KineticAbundance, Source.FightSpecific, BuffClassification.Other, BuffImages.KineticAbundance),
            new Buff("Enfeebled Force", EnfeebledForce, Source.FightSpecific, BuffClassification.Other, BuffImages.EnfeebledForce),
            new Buff("Backlashing Beam", BacklashingBeam, Source.FightSpecific, BuffClassification.Other, BuffImages.XerasBoon),
            new Buff("Clutched by Chaos", ClutchedByChaos, Source.FightSpecific, BuffClassification.Other, BuffImages.ProtectiveShadow),
            new Buff("Cleansed Conductor", CleansedConductor, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicBlastIntensity),
            new Buff("Poisoned Power", PoisonedPower, Source.FightSpecific, BuffClassification.Other, BuffImages.XerasFury),
            new Buff("Incorporeal", Incorporeal, Source.FightSpecific, BuffClassification.Other, BuffImages.MagicAura),
            new Buff("Flare-Up", FlareUp, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.MagicAura),
            new Buff("Unbridled Chaos", UnbridledChaos, Source.FightSpecific, BuffStackType.Stacking, 3, BuffClassification.Other, BuffImages.ExposedEyes),
            new Buff("Rebellious Power", RebelliousPower, Source.FightSpecific, BuffStackType.Stacking, 40, BuffClassification.Other, BuffImages.InfusedShield),
            new Buff("Charged Soul", ChargedSoul, Source.FightSpecific, BuffStackType.Stacking, 20, BuffClassification.Other, BuffImages.PartiallyProtected),
            new Buff("Breakbar Target", QadimThePeerlessBreakbarTargetBuff, Source.FightSpecific, BuffClassification.Hidden, BuffImages.Unknown),
            new Buff("Achievement Eligibility: Power Surge", AchievementEligibilityPowerSurge, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            //////////////////////////////////////////////
            // Fractals 
            new Buff("Rigorous Certainty", RigorousCertainty, Source.Common, BuffClassification.Defensive, BuffImages.DesertCarapace),
            new Buff("Fractal Savant", FractalSavant, Source.Common, BuffClassification.Offensive, BuffImages.Malign9Infusion),
            new Buff("Fractal Prodigy", FractalProdigy, Source.Common, BuffClassification.Offensive, BuffImages.Mighty9Infusion),
            new Buff("Fractal Champion", FractalChampion, Source.Common, BuffClassification.Offensive, BuffImages.Precise9Infusion),
            new Buff("Fractal God", FractalGod, Source.Common, BuffClassification.Offensive, BuffImages.Healing9Infusion),
            new Buff("Debilitated (Toxic Sickness)", DebilitatedToxicSickness, Source.FightSpecific, BuffStackType.Stacking, 3, BuffClassification.Debuff, BuffImages.Debilitated),
            new Buff("Agony", Agony, Source.FightSpecific,BuffStackType.Stacking, 25, BuffClassification.Debuff, BuffImages.Agony),
            new Buff("Hamstrung", Hamstrung, Source.FightSpecific,BuffStackType.Stacking, 99, BuffClassification.Debuff, BuffImages.Hamstrung).WithBuilds(GW2Builds.StartOfLife, GW2Builds.July2022FractalInstabilitiesRework),
            new Buff("Hamstrung", Hamstrung, Source.FightSpecific,BuffStackType.Stacking, 33, BuffClassification.Debuff, BuffImages.Hamstrung).WithBuilds(GW2Builds.July2022FractalInstabilitiesRework),
            new Buff("Sticking Together", StickingTogetherBuff, Source.FightSpecific, BuffClassification.Offensive, BuffImages.ActivateGreen),
            new Buff("Not Sticking Together", NotStickingTogetherBuff, Source.FightSpecific, BuffClassification.Debuff, BuffImages.ActivateRed),
            new Buff("Social Awkwardness Immunity", SocialAwkwardnessImmunity, Source.FightSpecific, BuffClassification.Other, BuffImages.ActivateYellow),
            // Siax 
            new Buff("Fixated (Nightmare)", FixatedNightmare, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            // Ensolyss 
            new Buff("Determination (Ensolyss)", DeterminationEnsolyss, Source.FightSpecific, BuffClassification.Other, BuffImages.GambitExhausted),
            // Shattered Observatory
            new Buff("Achievement Eligibility: Be Dynamic", AchievementEligibilityBeDynamic, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Cosmic Energy", CosmicEnergy, Source.FightSpecific, BuffClassification.Other, BuffImages.BreakOut),
            // Skorvald
            new Buff("Skorvald's Ire", SkorvaldsIre, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            // Artsariiv
            new Buff("Enraged (Fractal)", EnragedFractal, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Corporeal Reassignment", CorporealReassignmentBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.RedirectAnomaly),
            new Buff("Blinding Radiance", BlindingRadiance, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Determination (Viirastra)", DeterminationViirastra, Source.FightSpecific, BuffClassification.Other, BuffImages.GambitExhausted),
            new Buff("Nova Launch", NovaLaunchBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.CelestialDash),
            // Arkk 
            new Buff("Fixated (Bloom 3)", FixatedBloom3, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Bloom 2)", FixatedBloom2, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Bloom 1)", FixatedBloom1, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Bloom 4)", FixatedBloom4, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Cosmic Meteor", CosmicMeteor, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Diaphanous Shielding", DiaphanousShielding, Source.FightSpecific, BuffStackType.Stacking, 4, BuffClassification.Other, BuffImages.DiaphanousShielding),
            new Buff("Electrocuted", Electrocuted, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.AirAttunement),
            new Buff("Hypernova Launch", HypernovaLaunchBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.CelestialDash),
            new Buff("Reflective Shield", ReflectiveShieldBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.ReflectiveShielding),
            // Ai, Keeper of the Peak
            new Buff("Tidal Barrier", TidalBarrier, Source.FightSpecific, BuffClassification.Other, BuffImages.PrimedBottle),
            new Buff("Whirlwind Shield", WhirlwindShield, Source.FightSpecific, BuffClassification.Other, BuffImages.PrimedBottle),
            new Buff("Resilient Form", ResilientForm, Source.FightSpecific, BuffClassification.Other, BuffImages.CrowdFavor),
            new Buff("Cacophonous Mind", CacophonousMind, Source.FightSpecific, BuffStackType.Stacking, 20, BuffClassification.Other, BuffImages.TwistedEarth),
            new Buff("Crushing Guilt", CrushingGuilt, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.GuiltExploitation),
            new Buff("Fixated (Fear 3)", FixatedFear3, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Fear 2)", FixatedFear2, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Fear 1)", FixatedFear1, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Fixated (Fear 4)", FixatedFear4, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Charged Leap", ChargedLeap, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 3, BuffClassification.Other, BuffImages.IgniteArrowsDominion),
            new Buff("Tidal Bargain", TidalBargain, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.Waterlogged),
            new Buff("Achievement Eligibility: Dancing with Demons", AchievementEligibilityDancingWithDemons, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Energy Dispersal", AchievementEligibilityEnergyDispersal, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Kanaxai, Scythe of House Aurkus
            new Buff("Determined to Destroy", DeterminedToDestroy, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Determined (Kanaxai)", DeterminedKanaxai, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Phantasmagoria", Phantasmagoria, Source.FightSpecific, BuffClassification.Debuff, BuffImages.VoidAffliction),
            new Buff("Dread Defiance", DreadDefiance, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.IonShield),
            new Buff("Gathering Shadows", GatheringShadowsBuff, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.CaptainsInspiration),
            new Buff("Thess's Ward", ThesssWard, Source.FightSpecific, BuffClassification.Other, BuffImages.Hallucinations),
            new Buff("Spirit Fang", SpiritFang, Source.FightSpecific, BuffClassification.Other, BuffImages.ExposeWeakness),
            new Buff("Aspect Tether", AspectTetherBuff, Source.FightSpecific, BuffStackType.StackingTargetUniqueSrc, 999, BuffClassification.Other, BuffImages.Target),
            new Buff("Rending Storm Target (Axe 1)", RendingStormAxeTargetBuff1, Source.FightSpecific, BuffClassification.Other, BuffImages.ConjureFlameAxe),
            new Buff("Rending Storm Target (Axe 2)", RendingStormAxeTargetBuff2, Source.FightSpecific, BuffClassification.Other, BuffImages.ConjureFlameAxe),
            new Buff("Kanaxai Spread AoE", KanaxaiSpreadOrangeAoEBuff, Source.FightSpecific, BuffClassification.Hidden, BuffImages.Unknown),
            new Buff("Aspect Tether Available", AspectTetherAvailableBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.PowerOfTheVoid),
            new Buff("Aspect Tether Unavailable (Fear)", AspectOfFearNoTetherBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Exhaustion),
            new Buff("Aspect Tether Unavailable (Torment)", AspectOfTormentNoTetherBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Exhaustion),
            new Buff("Aspect Tether Unavailable (Exposure)", AspectOfExposureNoTetherBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Exhaustion),
            new Buff("Aspect Tether Unavailable (Death)", AspectOfDeathNoTetherBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Exhaustion),
            new Buff("Aspect Tether Unavailable (Lethargy)", AspectOfLethargyNoTetherBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Exhaustion),
            new Buff("Achievement Eligibility: Unsundered", AchievementEligibilityUnsundered, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: The Fearless Few", AchievementEligibilityTheFearlessFew, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Peace and Quiet", AchievementEligibilityPeaceAndQuiet, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Jade Sea Legs", AchievementEligibilityJadeSeaLegs, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Strike Mission
            new Buff("Exposed (Player)", ExposedPlayer, Source.Common, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.Exposed),
            // Icebrood
            new Buff("Hypothermia", Hypothermia, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Hypothermia),
            new Buff("Achievement Eligibility: Ice Breaker", AchievementEligibilityIceBreaker, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Smooth as Ice", AchievementEligibilitySmoothAsIce, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Fraenir of Jormag
            new Buff("Frozen", Frozen, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Frostbite),
            new Buff("Snowblind", Snowblind, Source.FightSpecific, BuffClassification.Other, BuffImages.Frostbite),
            new Buff("Bound Ice Elemental", BoundIceElemental, Source.FightSpecific, BuffClassification.Other, BuffImages.UnboundBlizzard),
            new Buff("Achievement Eligibility: Elemental Elegy", AchievementEligibilityElementalElegy, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Fraenir Frolic", AchievementEligibilityFraenirFrolic, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: High Shaman, High Stakes", AchievementEligibilityHighShamanHighStakes, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Voice and Claw
            new Buff("Unrelenting Pain", UnrelentingPainBuff, Source.FightSpecific, BuffClassification.Debuff, BuffImages.OverchargedGateGolem), // Founds on Kodans and Boneskinner
            new Buff("Enraged (V&C)", EnragedVC, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Achievement Eligibility: Break It Up", AchievementEligibilityBreakItUp, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Flawless Fallen", AchievementEligibilityFlawlessFallen, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Kodan Dodger", AchievementEligibilityKodanDodger, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Boneskinner
            new Buff("Tormenting Aura", TormentingAura, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Darkness),
            new Buff("Achievement Eligibility: Deathless Hunt", AchievementEligibilityDeathlessHunt, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Hold onto the Light", AchievementEligibilityHoldOntoTheLight, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Whisper of Jormag
            new Buff("Whisper Teleport (Out)", WhisperTeleportOut, Source.FightSpecific, BuffClassification.Other, BuffImages.EmergencyWaypoint),
            new Buff("Whisper Teleport (Back)", WhisperTeleportBack, Source.FightSpecific, BuffClassification.Other, BuffImages.EmergencyWaypoint),
            new Buff("Frigid Vortex", FrigidVortexBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Chains of Frost (Active)", ChainsOfFrostActive, Source.FightSpecific, BuffClassification.Other, BuffImages.SoulBinder),
            new Buff("Chains of Frost (Application)", ChainsOfFrostApplication, Source.FightSpecific, BuffClassification.Other, BuffImages.SoulBinder),
            new Buff("Brain Freeze", BrainFreeze, Source.FightSpecific, BuffStackType.Stacking, 20, BuffClassification.Other, BuffImages.Frostbite),
            new Buff("Lethal Coalescence", LethalCoalescenceBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Achievement Eligibility: Reflections in the Ice", AchievementEligibilityReflectionsInTheIce, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Slither-less", AchievementEligibilitySlitherLess, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Vortex, Interrupted", AchievementEligibilityVortexInterrupted, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Freezie
            new Buff("Icy Barrier", IcyBarrier, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.ShieldOfIce),
            new Buff("Aurora Beam Target", AuroraBeamTargetBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Giant Snowball Target", GiantSnowballFreezieTargetBuff1, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            // Mai Trin
            new Buff("Shared Destruction (Mai Trin)", SharedDestructionMaiTrin, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Shared Destruction CM (Mai Trin)", SharedDestructionMaiTrinCM, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Magnetic Bomb", MagneticBomb, Source.FightSpecific, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Immune to damage and conditions.", ImmuneToDamageAndConditions, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Fail-Safe Activated", FailSafeActivated, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            //new Buff("Mai Trin ???", 63858, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Mai Trin ?????", MaiTrinSomething, Source.FightSpecific, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Chaos and Destruction", ChaosAndDestruction, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Photon Saturation", PhotonSaturation, Source.FightSpecific, BuffClassification.Other, BuffImages.PhotonSaturation),
            new Buff("Laser Target (Green)", MaiTrinCMBeamsTargetGreen, Source.FightSpecific, BuffClassification.Other, BuffImages.SynergeticLightAttunementGreen),
            new Buff("Laser Target (Red)", MaiTrinCMBeamsTargetRed, Source.FightSpecific, BuffClassification.Other, BuffImages.StaticLightAttunementRed),
            new Buff("Laser Target (Blue)", MaiTrinCMBeamsTargetBlue, Source.FightSpecific, BuffClassification.Other, BuffImages.DynamicLightAttunementBlue),
            new Buff("Achievement Eligibility: Leaps Abound", AchievementEligibilityLeapsAbound, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Total Coverage", AchievementEligibilityTotalCoverage, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Triangulation", AchievementEligibilityTriangulation, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Ankka
            new Buff("Necrotic Ritual", NecroticRitual, Source.FightSpecific, BuffClassification.Other, BuffImages.PoweredShielding),
            new Buff("Ankka ???", AnkkaPlateformChanging, Source.FightSpecific, BuffClassification.Other, BuffImages.Windfall),
            new Buff("Hallucinations", Hallucinations, Source.FightSpecific, BuffClassification.Other, BuffImages.Hallucinations),
            new Buff("Energy Transfer", EnergyTransfer, Source.FightSpecific, BuffClassification.Other, BuffImages.LocustTrail),
            new Buff("Death's Embrace", DeathsEmbraceNMCMBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Death's Embrace 2", DeathsEmbraceNMBuff, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 25, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Power of the Void", PowerOfTheVoid, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.PowerOfTheVoid),
            new Buff("Enraged (Ankka)", EnragedAnkka, Source.FightSpecific, BuffClassification.Other, BuffImages.Enraged),
            new Buff("Debilitating Void", DebilitatingVoid, Source.FightSpecific, BuffClassification.Debuff, BuffImages.ArcingAffliction).WithBuilds(GW2Builds.StartOfLife, GW2Builds.May2022Balance),
            new Buff("Debilitating Void", DebilitatingVoid, Source.FightSpecific, BuffClassification.Debuff, BuffImages.DebilitatingVoid).WithBuilds(GW2Builds.May2022Balance),
            new Buff("Devouring Void", DevouringVoid, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Debuff, BuffImages.Devour),
            new Buff("Sanctuary (Ankka 1)", SanctuaryAnkka1, Source.FightSpecific, BuffClassification.Other, BuffImages.GiftOfTrueSight),
            new Buff("Sanctuary (Ankka 2)", SanctuaryAnkka2, Source.FightSpecific, BuffClassification.Other, BuffImages.GiftOfTrueSight),
            new Buff("Imminent Death", ImminentDeathBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.UnboundDeathPool),
            new Buff("Ankka Lich Hallucination Fixation", AnkkaLichHallucinationFixation, Source.FightSpecific, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Death's Hand Spread", DeathsHandSpreadBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Achievement Eligibility: Clarity", AchievementEligibilityClarity, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Gaze into the Void", AchievementEligibilityGazeIntoTheVoid, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Undevoured", AchievementEligibilityUndevoured, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Minister Li   
            new Buff("Target Order: 1", TargetOrder1, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetOrder1),
            new Buff("Target Order: 2", TargetOrder2, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetOrder2),
            new Buff("Target Order: 3", TargetOrder3, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetOrder3),
            new Buff("Target Order: 4", TargetOrder4, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetOrder4),
            new Buff("Target Order: 5", TargetOrder5, Source.FightSpecific, BuffClassification.Other, BuffImages.TargetOrder5),
            new Buff("Stronger Together", StrongerTogether, Source.FightSpecific, BuffClassification.Other, BuffImages.GiantGrowth),
            new Buff("Vitality Equalizer 1", VitalityEqualizer1, Source.FightSpecific, BuffClassification.Other, BuffImages.SynchronizedVitality),
            new Buff("Vitality Equalizer CM", VitalityEqualizerCM, Source.FightSpecific, BuffClassification.Other, BuffImages.SynchronizedVitality),
            new Buff("Vitality Equalizer 2", VitalityEqualizer2, Source.FightSpecific, BuffClassification.Other, BuffImages.SynchronizedVitality),
            new Buff("Destructive Aura", DestructiveAuraBuff, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 10, BuffClassification.Other, BuffImages.ToxicGas),
            new Buff("Enhanced Destructive Aura", EnhancedDestructiveAuraBuff, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 10, BuffClassification.Other, BuffImages.ToxicGas),
            new Buff("Equalization Matrix", EqualizationMatrix, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.EqualizationMatrix),
            new Buff("Lethal Inspiration", LethalInspiration, Source.FightSpecific, BuffStackType.Stacking, 1, BuffClassification.Other, BuffImages.PowerOfTheVoid),
            new Buff("Extreme Vulnerability", ExtremeVulnerability, Source.FightSpecific, BuffClassification.Debuff, BuffImages.ExtremeVulnerability),
            new Buff("Fixated (Ankka & Kaineng Overlook)", FixatedAnkkaKainengOverlook, Source.FightSpecific, BuffStackType.StackingTargetUniqueSrc, 999, BuffClassification.Other, BuffImages.Fixated),
            //new Buff("Shared Destruction (Li)", PoV_SharedDestructionLi, Source.FightSpecific, BuffClassification.Other, BuffImages.MonsterSkill),
            //new Buff("Shared Destruction (Li CM)", PoV_SharedDestructionLiCM, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 25, BuffClassification.Other, BuffImages.MonsterSkill),
            new Buff("Debilitated", Debilitated, Source.FightSpecific, BuffStackType.Stacking, 3, BuffClassification.Debuff, BuffImages.Debilitated),
            new Buff("Infirmity", Infirmity, Source.FightSpecific, BuffStackType.Stacking, 4, BuffClassification.Debuff, BuffImages.DebilitatingVoid),
            new Buff("Disoriented", DisorientedBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Disoriented),
            // Harvest Temple
            new Buff("Influence of the Void", InfluenceOfTheVoidBuff, Source.FightSpecific, BuffStackType.Stacking, 20, BuffClassification.Other, BuffImages.ThrowCursedArtifact),
            new Buff("Targeted (Dragon Void)", TargetedDragonVoid, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Void Repulsion 1", VoidRepulsion1, Source.FightSpecific, BuffClassification.Other, BuffImages.FrozenBarrier),
            new Buff("Void Repulsion 2", VoidRepulsion2, Source.FightSpecific, BuffClassification.Other, BuffImages.FrozenBarrier),
            new Buff("Aerial Defense", AerialDefense, Source.FightSpecific, BuffClassification.Other, BuffImages.VinetenderShield),
            new Buff("Void Immunity", VoidImmunity, Source.FightSpecific, BuffClassification.Other, BuffImages.ActivatePurple),
            new Buff("Void Empowerment", VoidEmpowerment, Source.FightSpecific, BuffStackType.StackingConditionalLoss, 25, BuffClassification.Other, BuffImages.IgniteArrowsDominion),
            new Buff("Void Shell", VoidShell, Source.FightSpecific, BuffStackType.Stacking, 3, BuffClassification.Other, BuffImages.DetonateStaticConduit),
            new Buff("Achievement Eligibility: Jumping the Nope Ropes", AchievementEligibilityJumpingTheNopeRopes, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Standing Together", AchievementEligibilityStandingTogether, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Voidwalker", AchievementEligibilityVoidwalker, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // new Buff("POV Share The Void Counter", POV_ShareTheVoidCounter, Source.FightSpecific, BuffStackType.Stacking, 25, BuffClassification.Other, BuffImages.AchievementEffect), // Counts successful greens, POV only
            // Old Lion's Court
            new Buff("Fixated (Old Lion's Court)", FixatedOldLionsCourt, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.Fixated),
            new Buff("Ergo Shear", ErgoShear, Source.FightSpecific, BuffClassification.Other, BuffImages.ErgoShear),
            new Buff("Ergo Shear CM", ErgoShearCM, Source.FightSpecific, BuffClassification.Other, BuffImages.ErgoShear),
            new Buff("Tidal Torment", TidalTorment, Source.FightSpecific, BuffClassification.Other, BuffImages.TidalTorment),
            new Buff("Tidal Torment CM", TidalTormentCM, Source.FightSpecific, BuffClassification.Other, BuffImages.TidalTorment),
            new Buff("Naked Singularity", NakedSingularity, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Naked Singularity CM", NakedSingularityCM, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Ley-Woven Shielding", LeyWovenShielding, Source.FightSpecific, BuffClassification.Other, BuffImages.LeyEnergyShield),
            new Buff("Malfunctioning Ley-Woven Shielding", MalfunctioningLeyWovenShielding, Source.FightSpecific, BuffClassification.Other, BuffImages.Unblockable),
            new Buff("Power Transfer", PowerTransfer, Source.FightSpecific, BuffStackType.Queue, 99, BuffClassification.Other, BuffImages.SpiritEnergyTracker),
            new Buff("Empowered (Watchknight Triumverate)", EmpoweredWatchknightTriumverate, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.ChargingEnergies),
            new Buff("Achievement Eligibility: Aether Aversion", AchievementEligibilityAetherAversion, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Fear Not This Knight", AchievementEligibilityFearNotThisKnight, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Static-Dynamic Synergy", AchievementEligibilityStaticDynamicSynergy, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            // Cosmic Observatory       
            new Buff("Residual Anxiety", ResidualAnxiety, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.ThrowCursedArtifact),
            new Buff("Beam of Light Duration", BeamOfLightDuration, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Dagda Phasing", DagdaDuringPhase75_50_25, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Soul Feast Something", SoulFeastSomethingBuff, Source.FightSpecific, BuffClassification.Hidden, BuffImages.Unknown),
            new Buff("Lost Control (Cosmic Observatory)", CosmicObservatoryLostControlBuff, Source.FightSpecific, BuffClassification.Debuff, BuffImages.Unknown),
            new Buff("Shooting Stars Target", ShootingStarsTargetBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Target),
            new Buff("Demonic Aura", DagdaDemonicAura, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Other, BuffImages.ChampionOfTheCrown),
            new Buff("Demonic Aura Timer", DagdaDemonicAuraTimer, Source.FightSpecific, BuffClassification.Other, BuffImages.ExposeWeakness),
            new Buff("Planetary Weight", PlanetaryWeight, Source.FightSpecific, BuffStackType.Stacking, 6, BuffClassification.Other, BuffImages.ChallengeOfTheAncients),
            new Buff("Summoned Phantom", SummonedPhantom, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Immune to Damage", ImmuneToDamage, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Shared Destruction Target (Meteor Crash)", DagdaSharedDestruction_MeteorCrash, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            // Temple of Febe
            new Buff("Insatiable", Insatiable, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.VoidCorruption),
            new Buff("Malicious Intent Target", MaliciousIntentTargetBuff, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Empowered (Cerus)", EmpoweredCerus, Source.FightSpecific, BuffStackType.Stacking, 99, BuffClassification.Other, BuffImages.EmpoweredMursaarOverseer),
            new Buff("Empowered Despair (Cerus)", EmpoweredDespairCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Envy (Cerus)", EmpoweredEnvyCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Gluttony (Cerus)", EmpoweredGluttonyCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Malice (Cerus)", EmpoweredMaliceCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Rage (Cerus)", EmpoweredRageCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Regret (Cerus)", EmpoweredRegretCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Despair (Embodiment)", EmpoweredDespairEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Envy (Embodiment)", EmpoweredEnvyEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Gluttony (Embodiment)", EmpoweredGluttonyEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Malice (Embodiment)", EmpoweredMaliceEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Rage (Embodiment)", EmpoweredRageEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Empowered Regret (Embodiment)", EmpoweredRegretEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.ExcessMagic),
            new Buff("Kryptis-Possessed", KryptisPossessed, Source.FightSpecific, BuffClassification.Other, BuffImages.Unknown),
            new Buff("Invulnerability (Cerus)", InvulnerabilityCerus, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            new Buff("Invulnerability (Embodiment)", InvulnerabilityEmbodiment, Source.FightSpecific, BuffClassification.Other, BuffImages.Determined),
            //Open World Soo-Won
            new Buff("Jade Tech Offensive Overcharge", JadeTechOffensiveOvercharge, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Offensive, BuffImages.JadeTechOffensive),
            new Buff("Jade Tech Defensive Overcharge", JadeTechDefensiveOvercharge, Source.FightSpecific, BuffStackType.Queue, 9, BuffClassification.Defensive, BuffImages.JadeTechDefensive),
            new Buff("Enhancement (+5% Damage vs. Dragonvoid)", EnhancementDragonsEnd, Source.FightSpecific, BuffClassification.Offensive, BuffImages.NourishmentUtility),
            new Buff("Soul Reunited", SoulReunited, Source.FightSpecific, BuffClassification.Offensive, BuffImages.AllysAidPoweredUp),
            new Buff("Wisp Form", WispForm, Source.FightSpecific, BuffClassification.Other, BuffImages.FracturedSpirit),
            new Buff("Void Corruption", VoidCorruption, Source.FightSpecific, BuffStackType.Stacking, 10, BuffClassification.Debuff, BuffImages.VoidCorruption),
            new Buff("Void Chaos", VoidChaos, Source.FightSpecific, BuffClassification.Debuff, BuffImages.SpectralAgony),
            new Buff("Hardened Shell", HardenedShell, Source.FightSpecific, BuffClassification.Other, BuffImages.DefensiveInspiration),
            new Buff("Dragon's End Contributor 1", DragonsEndContributor1, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale01),
            new Buff("Dragon's End Contributor 2", DragonsEndContributor2, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale02),
            new Buff("Dragon's End Contributor 3", DragonsEndContributor3, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale03),
            new Buff("Dragon's End Contributor 4", DragonsEndContributor4, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale04),
            new Buff("Dragon's End Contributor 5", DragonsEndContributor5, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale05),
            new Buff("Dragon's End Contributor 6", DragonsEndContributor6, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale06),
            new Buff("Dragon's End Contributor 7", DragonsEndContributor7, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale07),
            new Buff("Dragon's End Contributor 8", DragonsEndContributor8, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale08),
            new Buff("Dragon's End Contributor 9", DragonsEndContributor9, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale09),
            new Buff("Dragon's End Contributor 10", DragonsEndContributor10, Source.FightSpecific, BuffClassification.Support, BuffImages.SeraphMorale10),
            new Buff("Achievement Eligibility: Competent Commander", AchievementEligibilityCompetentCommander, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: The Floor Is Void", AchievementEligibilityTheFloorIsVoid, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: True Ending", AchievementEligibilityTrueEnding, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
            new Buff("Achievement Eligibility: Untarnished Spirits", AchievementEligibilityUntarnishedSpirits, Source.FightSpecific, BuffClassification.Other, BuffImages.AchievementEffect),
        };

    }
}
