using System.Collections.Generic;
using GW2EIEvtcParser.ParserHelpers;
using static GW2EIEvtcParser.EIData.Buff;
using static GW2EIEvtcParser.ParserHelper;
using static GW2EIEvtcParser.SkillIDs;

namespace GW2EIEvtcParser.EIData
{
    internal static class FoodBuffs
    {
        internal static readonly List<Buff> NormalFoods = new List<Buff>
        {
            new Buff("Malnourished", Malnourished, Source.Item, BuffClassification.Nourishment, BuffImages.Malnourished),
            new Buff("Plate of Truffle Steak", PlateOfTruffleSteak, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfTruffleSteak),
            new Buff("Bowl of Sweet and Spicy Butternut Squash Soup", BowlOfSweetAndSpicyButternutSquashSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSweetAndSpicyButternutSquashSoup),
            new Buff("Bowl of Curry Butternut Squash Soup", BowlOfCurryButternutSquashSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCurryButternutSquashSoup),
            new Buff("Bowl of Fancy Potatoe and Leek Soup", BowlOfFancyPotatoeAndLeekSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFancyPotatoeAndLeekSoup),
            new Buff("Red-Lentil Saobosa", RedLentilSaobosa, Source.Item, BuffClassification.Nourishment, BuffImages.RedLentilSaobosa),
            new Buff("Super Veggie Pizza", SuperVeggiePizza, Source.Item, BuffClassification.Nourishment, BuffImages.SuperVeggiePizza),
            new Buff("Rare Veggie Pizza", RareVeggiePizza, Source.Item, BuffClassification.Nourishment, BuffImages.RareVeggiePizza),
            new Buff("Bowl of Garlic Kale Sautee", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfGarlicKaleSautee),
            new Buff("Koi Cake", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.KoiCake),
            new Buff("Prickly Pear Pie", PricklyPearPie, Source.Item, BuffClassification.Nourishment, BuffImages.PricklyPearPie),
            new Buff("Bowl of Nopalitos Sauté", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfNopalitosSaute),
            new Buff("Loaf of Candy Cactus Cornbread", LoafOfCandyCactusCornbread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfCandyCactusCornbread),
            new Buff("Delicious Rice Ball", DeliciousRiceBall, Source.Item, BuffClassification.Nourishment, BuffImages.DeliciousRiceBall),
            new Buff("Slice of Allspice Cake", SliceOfAllspiceCake, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfAllspiceCake),
            new Buff("Fried Golden Dumpling", FriedGoldenDumpling, Source.Item, BuffClassification.Nourishment, BuffImages.FriedGoldenDumpling),
            new Buff("Bowl of Seaweed Salad", BowlOfSeaweedSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSeaweedSalad),
            new Buff("Bowl of Orrian Truffle and Meat Stew", BowlOfOrrianTruffleAndMeatStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfOrrianTruffleAndMeatStew),
            new Buff("Plate of Mussels Gnashblade", PlateOfMusselsGnashblade, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfMusselsGnashblade),
            new Buff("Spring Roll", SpringRoll, Source.Item, BuffClassification.Nourishment, BuffImages.SpringRoll),
            new Buff("Plate of Beef Rendang", PlateOfBeefRendang, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfBeefRendang),
            new Buff("Dragon's Revelry Starcake", DragonsRevelryStarcake, Source.Item, BuffClassification.Nourishment, BuffImages.DragonsRevelryStarcake),
            new Buff("Avocado Smoothie", AvocadoSmoothie, Source.Item, BuffClassification.Nourishment, BuffImages.AvocadoSmoothie),
            new Buff("Carrot Souffle", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.CarrotSouffle), //same as Dragon's_Breath_Bun
            new Buff("Plate of Truffle Steak Dinner", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfTruffleSteakDinner), //same as Dragon's Breath Bun
            new Buff("Dragon's Breath Bun", DragonsBreathBun, Source.Item, BuffClassification.Nourishment, BuffImages.DragonsBreathBun),
            new Buff("Karka Egg Omelet", KarkaEggOmelet, Source.Item, BuffClassification.Nourishment, BuffImages.KarkaEggOmelet),
            new Buff("Steamed Red Dumpling", SteamedRedDumpling, Source.Item, BuffClassification.Nourishment, BuffImages.SteamedRedDumpling),
            new Buff("Saffron Stuffed Mushroom", Unknown, Source.Item, BuffClassification.Nourishment, BuffImages.SaffronStuffedMushroom), //same as Karka Egg Omelet
            new Buff("Soul Pastry", SoulPastry, Source.Item, BuffClassification.Nourishment, BuffImages.SoulPastry),
            new Buff("Bowl of Fire Meat Chili", BowlOfFireMeatChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFireMeatChili),
            new Buff("Plate of Fire Flank Steak", PlateOfFireFlankSteak, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfFireFlankSteak),
            new Buff("Plate of Orrian Steak Frittes", PlateOfOrrianSteakFrittes, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfOrrianSteakFrittes),
            new Buff("Spicier Flank Steak", SpicierFlankSteak, Source.Item, BuffClassification.Nourishment, BuffImages.SpicierFlankSteak),
            new Buff("Mango Pie", MangoPie, Source.Item, BuffClassification.Nourishment, BuffImages.MangoPie),
            new Buff("Block of Tofu", BlockOfTofu, Source.Item, BuffClassification.Nourishment, BuffImages.BlockOfTofu),
            new Buff("Fishy Rice Bowl", FishyRiceBowl, Source.Item, BuffClassification.Nourishment, BuffImages.FishyRiceBowl),
            new Buff("Meaty Rice Bowl", MeatyRiceBowl, Source.Item, BuffClassification.Nourishment, BuffImages.MeatyRiceBowl),
            new Buff("Plate of Kimchi Pancakes", PlateOfKimchiPancakes, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfKimchiPancakes),
            new Buff("Bowl of Kimchi Tofu Stew", BowlOfKimchiTofuStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfKimchiTofuStew),
            new Buff("Meaty Asparagus Skewer", MeatyAsparagusSkewer, Source.Item, BuffClassification.Nourishment, BuffImages.MeatyAsparagusSkewer),
            new Buff("Bloodstone Bisque", BloodstoneBisque, Source.Item, BuffClassification.Nourishment, BuffImages.BloodstoneBisque),
            new Buff("Plate of Spicy Moa Wings", PlateOfSpicyMoaWings, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSpicyMoaWings),
            new Buff("Steak with Winterberry Sauce", SteakWithWinterberrySauce, Source.Item, BuffClassification.Nourishment, BuffImages.SteakWithWinterberrySauce),
            new Buff("Feast of Delectable Birthday Cake", FeastOfDelectableBirthdayCake, Source.Item, BuffClassification.Nourishment, BuffImages.FeastOfDelectableBirthdayCake),
            new Buff("Jerk Poultry and Nopal Flatbread Sandwich", JerkPoultryAndNopallFlatbreadSandwich, Source.Item, BuffClassification.Nourishment, BuffImages.JerkPoultryAndNopallFlatbreadSandwich),
            new Buff("Spicy Flank Steak", SpicyFlankSteak, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyFlankSteak),
            new Buff("Plate of Jerk Poultry", PlateOfJerkPoultry, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfJerkPoultry),
            new Buff("Spicy Marinated Mushroom", SpicyMarinatedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyMarinatedMushroom),
            new Buff("Bowl of Passion Fruit Tapioca Pudding", BowlOfPassionFruitTapiocaPudding, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPassionFruitTapiocaPudding),
            new Buff("Bowl of Sawgill Mushroom Risotto", BowlOfSawgillMushroomRisotto, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSawgillMushroomRisotto),
            new Buff("Bowl of Curry Pumpkin Soup", BowlOfCurryPumpkinSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCurryPumpkinSoup),
            new Buff("Plate of Spicy Herbed Chicken", PlateOfSpicyHerbedChicken, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSpicyHerbedChicken),
            new Buff("Bowl of Tropical Mousse", BowlOfTropicalMousse, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfTropicalMousse),
            new Buff("Bowl of Chocolate Tapioca Pudding", BowlOfChocolateTapiocaPudding, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChocolateTapiocaPudding),
            new Buff("Bowl of Refugee's Beet Soup", BowlOfRefugeesBeetSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfRefugeesBeetSoup),
            new Buff("Flatbread", Flatbread, Source.Item, BuffClassification.Nourishment, BuffImages.Flatbread),
            new Buff("Mushroom Loaf", MushroomLoaf, Source.Item, BuffClassification.Nourishment, BuffImages.MushroomLoaf),
            new Buff("Loaf of Omnomberry Bread", LoafOfOmnomberryBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfOmnomberryBread),
            new Buff("Bowl of Zesty Turnip Soup", BowlOfZestyTurnipSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfZestyTurnipSoup),
            new Buff("Plate of Eggs Benedict", PlateOfEggsBenedict, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfEggsBenedict),
            new Buff("Bowl of Firebreather Chili", BowlOfFirebreatherChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFirebreatherChili),
            new Buff("Bowl of Green Chile Ice Cream", BowlOfGreenChileIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfGreenChileIceCream),
            new Buff("Bowl of Carne Khan Chili", BowlOfCarneKhanChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCarneKhanChili),
            new Buff("Bowl of Truffle Risotto", BowlOfTruffleRisotto, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfTruffleRisotto),
            new Buff("Bowl of Orrian Truffle Soup", BowlOfOrrianTruffleSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfOrrianTruffleSoup),
            new Buff("Bowl of Prickly Pear Tapioca Pudding", BowlOfPricklyPearTapiocaPudding, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPricklyPearTapiocaPudding),
            new Buff("Bowl of Sweet and Spicy Beans", BowlOfSweetAndSpicyBeans, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSweetAndSpicyBeans),
            new Buff("Bowl of \"Elon Red\"", BowlOfElonRed, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfElonRed),
            new Buff("Chocolate Omnomberry Cake", ChocolateOmnomberryCake, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateOmnomberryCake),
            new Buff("Fancy Truffle Burger", FancyTruffleBurger, Source.Item, BuffClassification.Nourishment, BuffImages.FancyTruffleBurger),
            new Buff("Bowl of Fire Veggie Chili", BowlOfFireVeggieChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFireVeggieChili),
            new Buff("Bowl of Prickly Pear Sorber", BowlOfPricklyPearSorber, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPricklyPearSorber),
            new Buff("Winterberry Sorbet", WinterberrySorbet, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPricklyPearSorber),
            new Buff("Plate of Roasted Cactus", PlateOfRoastedCactus, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfRoastedCactus),
            new Buff("Spicy Chocolate Cookie", SpicyChocolateCookie, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyChocolateCookie),
            new Buff("Omnomberry Cookie", OmnomberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.OmnomberryCookie),
            new Buff("Bowl of Tropical Fruit Salad", BowlOfTropicalFruitSalad, Source.Item, BuffClassification.Nourishment,BuffImages.BowlOfTropicalFruitSalad),
            new Buff("Bowl of Poultry Satay", BowlOfPoultrySatay, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPoultrySatay),
            new Buff("Bowl of Saffron-scented Poultry Soup", BowlOfSaffronScentedPoultrySoup, Source.Item, BuffClassification.Nourishment,BuffImages.BowlOfSaffronScentedPoultrySoup),
            new Buff("Bowl of Saffron-Mango Ice Cream", BowlOfSaffronMangoIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSaffronMangoIceCream),
            new Buff("Whitefish Sushi", WhitefishSushi, Source.Item, BuffClassification.Nourishment, BuffImages.WhitefishSushi),
            new Buff("Yellowfish Sushi", YellowfishSushi, Source.Item, BuffClassification.Nourishment, BuffImages.YellowfishSushi),
            new Buff("Orangefish Sushi", OrangefishSushi, Source.Item, BuffClassification.Nourishment, BuffImages.OrangefishSushi),
            new Buff("Redfish Sushi", RedfishSushi, Source.Item, BuffClassification.Nourishment, BuffImages.RedfishSushi),
            new Buff("Bowl of Fish Stew", BowlOfFishStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFishStew),
            new Buff("Plate of Island Pudding", PlateOfIslandPudding, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfIslandPudding),
            new Buff("Dragonfly Cupcake", DragonflyCupcake, Source.Item, BuffClassification.Nourishment, BuffImages.DragonflyCupcake),
            new Buff("Chocolate Omnomberry Cream", ChocolateOmnomberryCream, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateOmnomberryCream),
            new Buff("Cup of Lotus Fries", CupOfLotusFries, Source.Item, BuffClassification.Nourishment, BuffImages.CupOfLotusFries),
            new Buff("Spicy Pumpkin Cookie", SpicyPumpkinCookie, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyPumpkinCookie),
            new Buff("Peppermint Omnomberry Bar", PeppermintOmnomberryBar, Source.Item, BuffClassification.Nourishment, BuffImages.PeppermintOmnomberryBar),
            new Buff("Can of Stewed Oysters", CanOfStewedOysters, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfStewedOysters),
            new Buff("Fried Oysters", FriedOysters, Source.Item, BuffClassification.Nourishment, BuffImages.FriedOysters),
            new Buff("Fried Oyster Sandwich", FriedOysterSandwich, Source.Item, BuffClassification.Nourishment, BuffImages.FriedOysterSandwich),
            new Buff("Oysters With Cocktail Sauce", OystersWithCocktailSauce, Source.Item, BuffClassification.Nourishment, BuffImages.OystersWithCocktailSauce),
            new Buff("Bowl of Lemongrass Mussel Pasta", BowlOfLemongrassMusselPasta, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfLemongrassMusselPasta),
            new Buff("Bowl of Mussel Soup", BowlOfMusselSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMusselSoup),
            new Buff("Oysters with Spicy Sauce", OystersWithSpicySauce, Source.Item, BuffClassification.Nourishment, BuffImages.OystersWithSpicySauce),
            new Buff("Oysters Gnashblade", OystersGnashblade, Source.Item, BuffClassification.Nourishment, BuffImages.OystersGnashblade),
            new Buff("Oysters with Zesty Sauce", OystersWithZestySauce, Source.Item, BuffClassification.Nourishment, BuffImages.OystersWithZestySauce),
            new Buff("Oysters with Pesto Sauce", OystersWithPestoSauce, Source.Item, BuffClassification.Nourishment, BuffImages.OystersWithPestoSauce),
            new Buff("Bowl of Curry Mussel Soup", BowlOfCurryMusselSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCurryMusselSoup),
            new Buff("Loaf of Saffron Bread", LoafOfSaffronBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfSaffronBread),
            new Buff("Bowl of Lemongrass Poultry Soup", BowlOfLemongrassPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfLemongrassPoultrySoup),
            new Buff("Sweet Bean Bun", SweetBeanBun, Source.Item, BuffClassification.Nourishment, BuffImages.SweetBeanBun),
            new Buff("Bowl of Roasted Lotus Root", BowlOfRoastedLotusRoot, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfRoastedLotusRoot),
            new Buff("Bowl of Cactus Soup", BowlOfCactusSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCactusSoup),
            new Buff("Tropical Peppermint Cake", TropicalPeppermintCake, Source.Item, BuffClassification.Nourishment, BuffImages.TropicalPeppermintCake),
            new Buff("Bowl of Red Lentil Soup", BowlOfRedLentilSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfRedLentilSoup),
            new Buff("Holographic Super Cake", HolographicSuperCake, Source.Item, BuffClassification.Nourishment, BuffImages.HolographicSuperCake),
            new Buff("Omnomberry Pie", OmnomberryPieAndSliceOfCandiedDragonRoll, Source.Item, BuffClassification.Nourishment, BuffImages.OmnomberryPie),
            new Buff("Scoop of Mintberry Swirl Ice Cream", ScoopOfMintberrySwirlIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.ScoopOfMintberrySwirlIceCream),
            new Buff("Omnomberry Ghost", OmnomberryGhost, Source.Item, BuffClassification.Nourishment, BuffImages.OmnomberryGhost),
            new Buff("Winterberry Pie", WinterberryPie, Source.Item, BuffClassification.Nourishment, BuffImages.WinterberryPie),
            new Buff("Slice of Allspice Cake with Ice Cream", SliceOfAllspiceCakeWithIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfAllspiceCakeWithIceCream),
            new Buff("Plate of Sugar Rib Roast", PlateOfSugarRibRoast, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSugarRibRoast),
            new Buff("Ghost Pepper Popper", GhostPepperPopper, Source.Item, BuffClassification.Nourishment, BuffImages.GhostPepperPopper),
            new Buff("Bowl of Marjorys Experimental Chili", BowlOfMarjorysExperimentalChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMarjorysExperimentalChili),
            new Buff("Bowl of Tapioca Pudding", BowlOfTapiocaPudding, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfTapiocaPudding),
            new Buff("Cheesy Cassava Roll", CheesyCassavaRoll, Source.Item, BuffClassification.Nourishment, BuffImages.CheesyCassavaRoll),
            new Buff("Bowl of Lotus Stirfry", BowlOfLotusStirfry, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfLotusStirfry),
            new Buff("Bowl of Truffle Sautee", BowlOfTruffleSautee, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfTruffleSautee),
            new Buff("Omnomberry Compote", OmnomberryCompote, Source.Item, BuffClassification.Nourishment, BuffImages.OmnomberryCompote),
            new Buff("Bowl of Asparagus and Sage Salad", BowlOfAsparagusAndSageSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfAsparagusAndSageSalad),
            new Buff("Bowl of Winterberry Seaweed Salad", BowlOfWinterberrySeaweedSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfWinterberrySeaweedSalad),
            new Buff("Jerk Poultry Flatbread Sandwich", JerkPoultryFlatbreadSandwich, Source.Item, BuffClassification.Nourishment, BuffImages.JerkPoultryFlatbreadSandwich),
            new Buff("Plate of Sweet Curried Mussels", PlateOfSweetCurriedMussels, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSweetCurriedMussels),
            new Buff("Bowl of Spiced Red Lentil Stew", BowlOfSpicedRedLentilStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicedRedLentilStew),
            new Buff("Tarragon Stuffed Poultry", TarragonStuffedPoultry, Source.Item, BuffClassification.Nourishment, BuffImages.TarragonStuffedPoultry),
            new Buff("Plate of Lemongrass Poultry", PlateOfLemongrassPoultry, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfLemongrassPoultry),
            new Buff("Cup of Light-Roasted Coffee", CupOfLightRoastedCoffee, Source.Item, BuffClassification.Nourishment, BuffImages.CupOfLightRoastedCoffee),
            new Buff("Bowl of Fire Salsa", BowlOfFireSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFireSalsa),
            new Buff("Bowl of Cold Wurm Stew", BowlOfColdWurmStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfColdWurmStew),
            new Buff("Stick of Mystery Meat", StickOfMysteryMeat, Source.Item, BuffClassification.Nourishment, BuffImages.StickOfMysteryMeat),
            new Buff("Filet of Sesame-Roasted Meat", FiletOfSesameRoastedMeat, Source.Item, BuffClassification.Nourishment, BuffImages.FiletOfSesameRoastedMeat),
            new Buff("Can of Steak and Asparagus", CanOfSteakAndAsparagus, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfSteakAndAsparagus),
            new Buff("Plate of Steak and Asparagus", PlateOfSteakAndAsparagus, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSteakAndAsparagus),
            new Buff("Plate of Coriander Crusted Meat", PlateOfCorianderCrustedMeat, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCorianderCrustedMeat),
            new Buff("Filet of Rosemary-Roasted Meat", FiletOfRosemaryRoastedMeat, Source.Item, BuffClassification.Nourishment, BuffImages.FiletOfRosemaryRoastedMeat),
            new Buff("Plate of Roast Meat with Mint Sauce", PlateOfRoastMeatWithMintSauce, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfRoastMeatWithMintSauce),
            new Buff("Plate of Roast Meat with Braised Leeks", PlateOfRoastMeatWithBraisedLeeks, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfRoastMeatWithBraisedLeeks),
            new Buff("Can of Roasted Meat with Braised Leeks", CanOfRoastedMeatWithBraisedLeeks, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfRoastedMeatWithBraisedLeeks),
            new Buff("Spicy Lime Steak", SpicyLimeSteak, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyLimeSteak),
            new Buff("Plate of Citrus Clove Meat", PlateOfCitrusCloveMeat, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCitrusCloveMeat),
            new Buff("Canned Spicier Flank Steak", CannedSpicierFlankSteak, Source.Item, BuffClassification.Nourishment, BuffImages.CannedSpicierFlankSteak),
            new Buff("Bowl of Simple Vegetable Soup", BowlOfSimpleVegetableSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleVegetableSoup),
            new Buff("Bowl of Ice Wurm Bisque", BowlOfIceWurmBisque, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfIceWurmBisque),
            new Buff("Bowl of Kale Soup", BowlOfKaleSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfKaleSoup),
            new Buff("Bowl of Chickpea Soup", BowlOfChickpeaSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChickpeaSoup),
            new Buff("Bowl of Artichoke Soup", BowlOfArtichokeSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfArtichokeSoup),
            new Buff("Can of Artichoke Soup", CanOfArtichokeSoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfArtichokeSoup),
            new Buff("Can of Potato and Leek Soup", CanOfPotatoAndLeekSoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfPotatoAndLeekSoup),
            new Buff("Bowl of Potato and Leek Soup", BowlOfPotatoAndLeekSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPotatoAndLeekSoup),
            new Buff("Bowl of Pumpkin Bisque", BowlOfPumpkinBisque, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPumpkinBisque),
            new Buff("Bowl of Yam Soup", BowlOfYamSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfYamSoup),
            new Buff("Bowl of Tomato Zucchini Soup", BowlOfTomatoZucchiniSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfTomatoZucchiniSoup),
            new Buff("Bowl of Cauliflower Soup", BowlOfCauliflowerSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCauliflowerSoup),
            new Buff("Bowl of Butternut Squash Soup", BowlOfButternutSquashSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfButternutSquashSoup),
            new Buff("Can of Butternut Squash Soup", CanOfButternutSquashSoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfButternutSquashSoup),
            new Buff("Plate of Pasta with Tomato Sauce", PlateOfPastaWithTomatoSauce, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPastaWithTomatoSauce),
            new Buff("Meatball Dinner", MeatballDinner, Source.Item, BuffClassification.Nourishment, BuffImages.MeatballDinner),
            new Buff("Bowl of Krytan Meatball Dinner", BowlOfKrytanMeatballDinner, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfKrytanMeatballDinner),
            new Buff("Bowl of Pesto Pasta Salad", BowlOfPestoPastaSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPestoPastaSalad),
            new Buff("Bowl of Poultry Tarragon Pasta", BowlOfPoultryTarragonPasta, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPoultryTarragonPasta),
            new Buff("Can of Poultry Tarragon Pasta", CanOfPoultryTarragonPasta, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfPoultryTarragonPasta),
            new Buff("Plate of Frostgorge Clams", PlateOfFrostgorgeClams, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfFrostgorgeClams),
            new Buff("Bowl of Salad a la Consortium", BowlOfSaladALaConsortium, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSaladALaConsortium),
            new Buff("Passion Fruit Coconut Cookie", PassionFruitCoconutCookie, Source.Item, BuffClassification.Nourishment, BuffImages.PassionFruitCoconutCookie),
            new Buff("Canned Stuffed Artichoke with Tropical Dressing", CannedStuffedArtichokeWithTropicalDressing, Source.Item, BuffClassification.Nourishment, BuffImages.CannedStuffedArtichokeWithTropicalDressing),
            new Buff("Stuffed Artichoke with Tropical Dressing", StuffedArtichokeWithTropicalDressing, Source.Item, BuffClassification.Nourishment, BuffImages.StuffedArtichokeWithTropicalDressing),
            new Buff("Grumble Cake", GrumbleCake, Source.Item, BuffClassification.Nourishment, BuffImages.GrumbleCake),
            new Buff("Fried Banana Chips", FriedBananaChips, Source.Item, BuffClassification.Nourishment, BuffImages.FriedBananaChips),
            new Buff("Bowl of Dolyak Stew", BowlOfDolyakStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfDolyakStew),
            new Buff("Loaf of Banana Bread", LoafOfBananaBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfBananaBread),
            new Buff("Loaf of Zucchini Bread", LoafOfZucchiniBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfZucchiniBread),
            new Buff("Slice of Pumpkin Bread", SliceOfPumpkinBread, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfPumpkinBread),
            new Buff("Loaf of Raspberry Peach Bread", LoafOfRaspberryPeachBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfRaspberryPeachBread),
            new Buff("Can of Raspberry Peach Bread", CanOfRaspberryPeachBread, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfRaspberryPeachBread),
            new Buff("Grilled Mushroom", GrilledMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.GrilledMushroom),
            new Buff("Veggie Burger", VeggieBurger, Source.Item, BuffClassification.Nourishment, BuffImages.VeggieBurger),
            new Buff("Grilled Portobello Mushroom", GrilledPortobelloMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.GrilledPortobelloMushroom),
            new Buff("Bowl of Mushroom Risotto", BowlOfMushroomRisotto, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMushroomRisotto),
            new Buff("Bowl of Mushroom and Asparagus Risotto", BowlOfMushroomAndAsparagusRisotto, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMushroomAndAsparagusRisotto),
            new Buff("Bowl of Creamy Portobello Soup", BowlOfCreamyPortobelloSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCreamyPortobelloSoup),
            new Buff("Can of Mushroom and Asparagus Risotto", CanOfMushroomAndAsparagusRisotto, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfMushroomAndAsparagusRisotto),
            new Buff("Bowl of Fancy Creamy Mushroom Soup", BowlOfFancyCreamyMushroomSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFancyCreamyMushroomSoup),
            new Buff("Can of Snow Truffle Soup", CanOfSnowTruffleSoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfSnowTruffleSoup),
            new Buff("Bowl of Snow Truffle Soup", BowlOfSnowTruffleSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSnowTruffleSoup),
            new Buff("Cheese Pizza", CheesePizza, Source.Item, BuffClassification.Nourishment, BuffImages.CheesePizza),
            new Buff("Veggie Pizza", VeggiePizza, Source.Item, BuffClassification.Nourishment, BuffImages.VeggiePizza),
            new Buff("Mushroom Pizza", MushroomPizza, Source.Item, BuffClassification.Nourishment, BuffImages.MushroomPizza),
            new Buff("Fancy Veggie Pizza", FancyVeggiePizza, Source.Item, BuffClassification.Nourishment, BuffImages.FancyVeggiePizza),
            new Buff("Bowl of Simple Meat Chili", BowlOfSimpleMeatChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleMeatChili),
            new Buff("Bowl of Chili and Avocado", BowlOfChiliAndAvocado, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChiliAndAvocado),
            new Buff("Bowl of Spiced Meat Chili", BowlOfSpicedMeatChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicedMeatChili),
            new Buff("Bowl of Spicy Meat Chili", BowlOfSpicyMeatChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicyMeatChili),
            new Buff("Can of Spicy Meat Chili", CanOfSpicyMeatChili, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfSpicyMeatChili),
            new Buff("WhiteCake", WhiteCake, Source.Item, BuffClassification.Nourishment, BuffImages.WhiteCake),
            new Buff("Chocolate Cake", ChocolateCake, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateCake),
            new Buff("Chocolate Cherry Cake", ChocolateCherryCake, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateCherryCake),
            new Buff("Orange Coconut Cake", OrangeCoconutCake, Source.Item, BuffClassification.Nourishment, BuffImages.OrangeCoconutCake),
            new Buff("Chocolate Raspberry Cake", ChocolateRaspberryCake, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateRaspberryCake),
            new Buff("Canned Chocolate Raspberry Cake", CannedChocolateRaspberryCake, Source.Item, BuffClassification.Nourishment, BuffImages.CannedChocolateRaspberryCake),
            new Buff("Cheeseburger", Cheeseburger, Source.Item, BuffClassification.Nourishment, BuffImages.Cheeseburger),
            new Buff("Spinach Burger", SpinachBurger, Source.Item, BuffClassification.Nourishment, BuffImages.SpinachBurger),
            new Buff("Deluxe Burger", DeluxeBurger, Source.Item, BuffClassification.Nourishment, BuffImages.DeluxeBurger),
            new Buff("Horseradish Burger", HorseradishBurger, Source.Item, BuffClassification.Nourishment, BuffImages.HorseradishBurger),
            new Buff("Spicy Cheeseburger", SpicyCheeseburger, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyCheeseburger),
            new Buff("Boxed Spicy Cheeseburger", BoxedSpicyCheeseburger, Source.Item, BuffClassification.Nourishment, BuffImages.BoxedSpicyCheeseburger),
            new Buff("Bowl of Simple Bean Chili", BowlOfSimpleBeanChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleBeanChili),
            new Buff("Bowl of Fancy Bean Chili", BowlOfFancyBeanChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFancyBeanChili),
            new Buff("Bowl of Zucchini Chili", BowlOfZucchiniChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfZucchiniChili),
            new Buff("Bowl of Spiced Veggie Chili", BowlOfSpicedVeggieChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicedVeggieChili),
            new Buff("Bowl of Spicy Veggie Chili", BowlOfSpicyVeggieChili, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicyVeggieChili),
            new Buff("Sugar Cookie", SugarCookie, Source.Item, BuffClassification.Nourishment, BuffImages.SugarCookie),
            new Buff("Strawberry Cookie", StrawberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.StrawberryCookie),
            new Buff("Chocolate Chip Cookie", ChocolateChipCookie, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateChipCookie),
            new Buff("Candy Corn Cookie", CandyCornCookie, Source.Item, BuffClassification.Nourishment, BuffImages.CandyCornCookie),
            new Buff("Chocolate Mint Cookie", ChocolateMintCookie, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateMintCookie),
            new Buff("Chocolate Raspberry Cookie", ChocolateRaspberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateRaspberryCookie),
            new Buff("Glazed Chocolate Raspberry Cookie", GlazedChocolateRaspberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.GlazedChocolateRaspberryCookie),
            new Buff("Boxed Chocolate Raspberry Cookie", BoxedChocolateRaspberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.BoxedChocolateRaspberryCookie),
            new Buff("Cherry Cookie", CherryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.CherryCookie),
            new Buff("Blackberry Cookie", BlackberryCookie, Source.Item, BuffClassification.Nourishment, BuffImages.BlackberryCookie),
            new Buff("Peach Cookie", PeachCookie, Source.Item, BuffClassification.Nourishment, BuffImages.PeachCookie),
            new Buff("Boxed Peach Cookie", BoxedPeachCookie, Source.Item, BuffClassification.Nourishment, BuffImages.BoxedPeachCookie),
            new Buff("Cherry Passion Fruit Cake", CherryPassionFruitCake, Source.Item, BuffClassification.Nourishment, BuffImages.CherryPassionFruitCake),
            new Buff("Orange Passion Fruit Tart", OrangePassionFruitTart, Source.Item, BuffClassification.Nourishment, BuffImages.OrangePassionFruitTart),
            new Buff("Canned Raspberry Passion Fruit Compote", CannedRaspberryPassionFruitCompote, Source.Item, BuffClassification.Nourishment, BuffImages.CannedRaspberryPassionFruitCompote),
            new Buff("Raspberry Passion Fruit Compote", RaspberryPassionFruitCompote, Source.Item, BuffClassification.Nourishment, BuffImages.RaspberryPassionFruitCompote),
            new Buff("Bowl of Poultry Noodle Soup", BowlOfPoultryNoodleSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPoultryNoodleSoup),
            new Buff("Bowl of Savory Spinach and Poultry Soup", BowlOfSavorySpinachAndPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSavorySpinachAndPoultrySoup),
            new Buff("Bowl of Kale and Poultry Soup", BowlOfKaleAndPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfKaleAndPoultrySoup),
            new Buff("Bowl of Hearty Poultry Soup", BowlOfHeartyPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfHeartyPoultrySoup),
            new Buff("Bowl of Poultry and Winter Vegetable Soup", BowlOfPoultryAndWinterVegetableSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPoultryAndWinterVegetableSoup),
            new Buff("Can of Hearty Poultry Soup", CanOfHeartyPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfHeartyPoultrySoup),
            new Buff("Bowl of Chocolate Chip Ice Cream", BowlOfChocolateChipIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChocolateChipIceCream),
            new Buff("Bowl of Candy Corn Ice Cream", BowlOfCandyCornIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCandyCornIceCream),
            new Buff("Bowl of Blueberry Chocolate Chunk Ice Cream", BowlOfBlueberryChocolateChunkIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfBlueberryChocolateChunkIceCream),
            new Buff("Bowl of Ginger-Lime Ice Cream", BowlOfGingerLimeIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfGingerLimeIceCream),
            new Buff("Bowl of Mint Chocolate Chip Ice Cream", BowlOfMintChocolateChipIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMintChocolateChipIceCream),
            new Buff("Bowl of Peach Raspberry Swirl Ice Cream", BowlOfPeachRaspberrySwirlIceCream, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPeachRaspberrySwirlIceCream),
            new Buff("Meat Pie", MeatPie, Source.Item, BuffClassification.Nourishment, BuffImages.MeatPie),
            new Buff("Candied Apple", CandiedApple, Source.Item, BuffClassification.Nourishment, BuffImages.CandiedApple),
            new Buff("Caramel", Caramel, Source.Item, BuffClassification.Nourishment, BuffImages.Caramel),
            new Buff("Chocolate Banana", ChocolateBanana, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateBanana),
            new Buff("Lemon Bar", LemonBar, Source.Item, BuffClassification.Nourishment, BuffImages.LemonBar),
            new Buff("Candy Corn Cake", CandyCornCake, Source.Item, BuffClassification.Nourishment, BuffImages.CandyCornCake),
            new Buff("Turrón Slice", TurronSlice, Source.Item, BuffClassification.Nourishment, BuffImages.TurronSlice),
            new Buff("Cherry Tart", CherryTart, Source.Item, BuffClassification.Nourishment, BuffImages.CherryTart),
            new Buff("Ginger Pear Tart", GingerPearTart, Source.Item, BuffClassification.Nourishment, BuffImages.GingerPearTart),
            new Buff("Glazed Pear Tart", GlazedPearTart, Source.Item, BuffClassification.Nourishment, BuffImages.GlazedPearTart),
            new Buff("Peach Tart", PeachTart, Source.Item, BuffClassification.Nourishment, BuffImages.PeachTart),
            new Buff("Canned Peach Tart", CannedPeachTart, Source.Item, BuffClassification.Nourishment, BuffImages.CannedPeachTart),
            new Buff("Glazed Peach Tart", GlazedPeachTart, Source.Item, BuffClassification.Nourishment, BuffImages.GlazedPeachTart),
            new Buff("Strawberry Ghost", StrawberryGhost, Source.Item, BuffClassification.Nourishment, BuffImages.StrawberryGhost),
            new Buff("Chocolate Cherry", ChocolateCherry, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateCherry),
            new Buff("Chocolate Orange", ChocolateOrange, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateOrange),
            new Buff("Chocolate Raspberry Cream", ChocolateRaspberryCream, Source.Item, BuffClassification.Nourishment, BuffImages.ChocolateRaspberryCream),
            new Buff("Boxed Chocolate Raspberry Cream", BoxedChocolateRaspberryCream, Source.Item, BuffClassification.Nourishment, BuffImages.BoxedChocolateRaspberryCream),
            new Buff("Yam Fritter", YamFritter, Source.Item, BuffClassification.Nourishment, BuffImages.YamFritter),
            new Buff("Chickpea Fritter", ChickpeaFritter, Source.Item, BuffClassification.Nourishment, BuffImages.ChickpeaFritter),
            new Buff("Eggplant Fritter", EggplantFritter, Source.Item, BuffClassification.Nourishment, BuffImages.EggplantFritter),
            new Buff("Canned Eggplant Fritter", CannedEggplantFritter, Source.Item, BuffClassification.Nourishment, BuffImages.CannedEggplantFritter),
            new Buff("Cherry Almond Bar", CherryAlmondBar, Source.Item, BuffClassification.Nourishment, BuffImages.CherryAlmondBar),
            new Buff("Piece of Candy Corn Almond Brittle", PieceOfCandyCornAlmondBrittle, Source.Item, BuffClassification.Nourishment, BuffImages.PieceOfCandyCornAlmondBrittle),
            new Buff("Orange Coconut Bar", OrangeCoconutBar, Source.Item, BuffClassification.Nourishment, BuffImages.OrangeCoconutBar),
            new Buff("Boxed Raspberry Peach Bar", BoxedRaspberryPeachBar, Source.Item, BuffClassification.Nourishment, BuffImages.BoxedRaspberryPeachBar),
            new Buff("Homemade Campfire Treat", HomemadeCampfireTreat, Source.Item, BuffClassification.Nourishment, BuffImages.HomemadeCampfireTreat),
            new Buff("Raspberry Peach Bar", RaspberryPeachBar, Source.Item, BuffClassification.Nourishment, BuffImages.RaspberryPeachBar),
            new Buff("Omnomberry Bar", OmnomberryBar, Source.Item, BuffClassification.Nourishment, BuffImages.OmnomberryBar),
            new Buff("Longevity Noodles", LongevityNoodles, Source.Item, BuffClassification.Nourishment, BuffImages.LongevityNoodles),
            new Buff("Slice of Cinnamon Toast", SliceOfCinnamonToast, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfCinnamonToast),
            new Buff("Slice of Garlic Bread", SliceOfGarlicBread, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfGarlicBread),
            new Buff("Loaf of Rosemary Bread", LoafOfRosemaryBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfRosemaryBread),
            new Buff("Slice of Spiced Bread", SliceOfSpicedBread, Source.Item, BuffClassification.Nourishment, BuffImages.SliceOfSpicedBread),
            new Buff("Loaf of Tarragon Bread", LoafOfTarragonBread, Source.Item, BuffClassification.Nourishment, BuffImages.LoafOfTarragonBread),
            new Buff("Canned Tarragon Bread", CannedTarragonBread, Source.Item, BuffClassification.Nourishment, BuffImages.CannedTarragonBread),
            new Buff("Bowl of Simple Poultry Soup", BowlOfSimplePoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimplePoultrySoup),
            new Buff("Bowl of Clam Chowder", BowlOfClamChowder, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfClamChowder),
            new Buff("Spinach Salad", SpinachSalad, Source.Item, BuffClassification.Nourishment, BuffImages.SpinachSalad),
            new Buff("Bowl of Dilled Clam Chowder", BowlOfDilledClamChowder, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfDilledClamChowder),
            new Buff("Bowl of Chickpea and Poultry Soup", BowlOfChickpeaAndPoultrySoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChickpeaAndPoultrySoup),
            new Buff("Bowl of Poultry and Leek Soup", BowlOfPoultryAndLeekSoup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfPoultryAndLeekSoup),
            new Buff("Can of Poultry and Leek Soup", CanOfPoultryAndLeekSoup, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfPoultryAndLeekSoup),
            new Buff("Mashed Potato", MashedPotato, Source.Item, BuffClassification.Nourishment, BuffImages.MashedPotato),
            new Buff("Bowl of Outrider Stew", BowlOfOutriderStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfOutriderStew),
            new Buff("Bowl of Mashed Yams", BowlOfMashedYams, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMashedYams),
            new Buff("Roasted Rutabaga", RoastedRutabaga, Source.Item, BuffClassification.Nourishment, BuffImages.RoastedRutabaga),
            new Buff("Roasted Parsnip", RoastedParsnip, Source.Item, BuffClassification.Nourishment, BuffImages.RoastedParsnip),
            new Buff("Apple Pie", ApplePie, Source.Item, BuffClassification.Nourishment, BuffImages.ApplePie),
            new Buff("Bowl of Candy Corn Custard", BowlOfCandyCornCustard, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCandyCornCustard),
            new Buff("Heart-Shaped Cookie", HeartShapedCookie, Source.Item, BuffClassification.Nourishment, BuffImages.HeartShapedCookie),
            new Buff("Grape Pie", GrapePie, Source.Item, BuffClassification.Nourishment, BuffImages.GrapePie),
            new Buff("Pumpkin Pie", PumpkinPie, Source.Item, BuffClassification.Nourishment, BuffImages.PumpkinPie),
            new Buff("Glazed Pumpkin Pie", GlazedPumpkinPie, Source.Item, BuffClassification.Nourishment, BuffImages.GlazedPumpkinPie),
            new Buff("Peach Pie", PeachPie, Source.Item, BuffClassification.Nourishment, BuffImages.PeachPie),
            new Buff("Canned Peach Pie Filling", CannedPeachPieFilling, Source.Item, BuffClassification.Nourishment, BuffImages.CannedPeachPieFilling),
            new Buff("Blueberry Pie", BlueberryPieAndSliceOfRainbowCake, Source.Item, BuffClassification.Nourishment, BuffImages.BlueberryPieAndSliceOfRainbowCake),
            new Buff("Strawberry Pie", StrawberryPieAndCupcake, Source.Item, BuffClassification.Nourishment, BuffImages.StrawberryPieAndCupcake),
            new Buff("Cherry Pie", CherryPie, Source.Item, BuffClassification.Nourishment, BuffImages.CherryPie),
            new Buff("Blackberry Pie", BlackberryPie, Source.Item, BuffClassification.Nourishment, BuffImages.BlackberryPie),
            new Buff("Canned Mixed Berry Pie", CannedMixedBerryPie, Source.Item, BuffClassification.Nourishment, BuffImages.CannedMixedBerryPie),
            new Buff("Mixed Berry Pie", MixedBerryPie, Source.Item, BuffClassification.Nourishment, BuffImages.MixedBerryPie),
            new Buff("Can of Spicy Veggie Chili", CanOfSpicyVeggieChili, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfSpicyVeggieChili),
            new Buff("Chili Pepper Popper", ChiliPepperPopper, Source.Item, BuffClassification.Nourishment, BuffImages.ChiliPepperPopper),
            new Buff("Stuffed Pepper", StuffedPepper, Source.Item, BuffClassification.Nourishment,BuffImages.StuffedPepper),
            new Buff("Stuffed Zucchini", StuffedZucchini, Source.Item, BuffClassification.Nourishment, BuffImages.StuffedZucchini),
            new Buff("Bowl of Hummus", BowlOfHummus, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfHummus),
            new Buff("Roasted Artichoke", RoastedArtichoke, Source.Item, BuffClassification.Nourishment, BuffImages.RoastedArtichoke),
            new Buff("Canned Roasted Artichoke", CannedRoastedArtichoke, Source.Item, BuffClassification.Nourishment, BuffImages.CannedRoastedArtichoke),
            new Buff("Bowl of Simple Meat Stew", BowlOfSimpleMeatStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleMeatStew),
            new Buff("Bowl of Hearty Red Meat Stew", BowlOfHeartyRedMeatStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfHeartyRedMeatStew),
            new Buff("Bowl of Meat and Cabbage Stew", BowlOfMeatAndCabbageStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMeatAndCabbageStew),
            new Buff("Bowl of Spiced Meat and Cabbage Stew", BowlOfSpicedMeatAndCabbageStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicedMeatAndCabbageStew),
            new Buff("Can of Meat and Winter Vegetable Stew", CanOfMeatAndWinterVegetableStew, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfMeatAndWinterVegetableStew),
            new Buff("Bowl of Meat and Winter Vegetable Stew", BowlOfMeatAndWinterVegetableStew, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMeatAndWinterVegetableStew),
            new Buff("Bowl of Simple Stirfry", BowlOfSimpleStirfry, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleStirfry),
            new Buff("Bowl of Garlic Spinach Sautee", BowlOfGarlicSpinachSautee, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfGarlicSpinachSautee),
            new Buff("Bowl of Avocado Stirfry", BowlOfAvocadoStirfry, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfAvocadoStirfry),
            new Buff("Bowl of Eggplant Stirfry", BowlOfEggplantStirfry, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfEggplantStirfry),
            new Buff("Can of Eggplant Stir-Fry", CanOfEggplantStirfry, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfEggplantStirfry),
            new Buff("Bowl of Sauteed Zucchini with Nutmeg", BowlOfSauteedZucchiniWithNutmeg, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSauteedZucchiniWithNutmeg),
            new Buff("Bowl of Cauliflower Sautee", BowlOfCauliflowerSautee, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCauliflowerSautee),
            new Buff("Bowl of Eggplant Sautee", BowlOfEggplantSautee, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfEggplantSautee),
            new Buff("Can of Eggplant Saute", CanOfEggplantSaute, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfEggplantSaute),
            new Buff("Bowl of Blueberry Apple Compote", BowlOfBlueberryAppleCompote, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfBlueberryAppleCompote),
            new Buff("Bowl of Strawberry Apple Compote", BowlOfStrawberryAppleCompote, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfStrawberryAppleCompote),
            new Buff("Bowl of Cherry Vanilla Compote", BowlOfCherryVanillaCompote, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCherryVanillaCompote),
            new Buff("Bowl of Blackberry Pear Compote", BowlOfBlackberryPearCompote, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfBlackberryPearCompote),
            new Buff("Raspberry Peach Compote", RaspberryPeachCompote, Source.Item, BuffClassification.Nourishment, BuffImages.RaspberryPeachCompote),
            new Buff("Canned Raspberry Peach Compote", CannedRaspberryPeachCompote, Source.Item, BuffClassification.Nourishment, BuffImages.CannedRaspberryPeachCompote),
            new Buff("Bowl of Simple Salad", BowlOfSimpleSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSimpleSalad),
            new Buff("ExplorersKit", ExplorersKit, Source.Item, BuffClassification.Nourishment, BuffImages.ExplorersKit),
            new Buff("Bowl of Ascalonian Salad", BowlOfAscalonianSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfAscalonianSalad),
            new Buff("Bowl of Coleslaw", BowlOfColeslaw, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfColeslaw),
            new Buff("Bowl of Cabbage and Chickpea Salad", BowlOfCabbageAndChickpeaSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfCabbageAndChickpeaSalad),
            new Buff("Can of Asparagus and Sage Salad", CanOfAsparagusAndSageSalad, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfAsparagusAndSageSalad),
            new Buff("Spicy Meat Kabob", SpicyMeatKabob, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyMeatKabob),
            new Buff("Piece of Undersea Wurm Sushi", PieceOfUnderseaWurmSushi, Source.Item, BuffClassification.Nourishment, BuffImages.PieceOfUnderseaWurmSushi),
            new Buff("Pepper Steak Dinner", PepperSteakDinner, Source.Item, BuffClassification.Nourishment, BuffImages.PepperSteakDinner),
            new Buff("Chef's Tasting Platter", ChefsTastingPlatter, Source.Item, BuffClassification.Nourishment, BuffImages.ChefsTastingPlatter),
            new Buff("Sesame-Roasted Dinner", SesameRoastedDinner, Source.Item, BuffClassification.Nourishment, BuffImages.SesameRoastedDinner),
            new Buff("Plate of Coriander Crusted Meat Dinner", PlateOfCorianderCrustedMeatDinner, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCorianderCrustedMeatDinner),
            new Buff("Can of Steak and Asparagus Dinner", CanOfSteakAndAsparagusDinner, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfSteakAndAsparagusDinner),
            new Buff("Plate of Steak and Asparagus Dinner", PlateOfSteakAndAsparagusDinner, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSteakAndAsparagusDinner),
            new Buff("Canned Spicy Stuffed Mushroom", CannedSpicyStuffedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.CannedSpicyStuffedMushroom),
            new Buff("Marinated Mushroom", MarinatedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.MarinatedMushroom),
            new Buff("Sage-Stuffed Mushroom", SageStuffedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.SageStuffedMushroom),
            new Buff("Divinity Stuffed Mushroom", DivinityStuffedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.DivinityStuffedMushroom),
            new Buff("Eztlitl Stuffed Mushroom", EztlitlStuffedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.EztlitlStuffedMushroom),
            new Buff("Spicy Stuffed Mushroom", SpicyStuffedMushroom, Source.Item, BuffClassification.Nourishment, BuffImages.SpicyStuffedMushroom),
            new Buff("Sage-Stuffed Poultry", SageStuffedPoultry, Source.Item, BuffClassification.Nourishment, BuffImages.SageStuffedPoultry),
            new Buff("Poultry Piccata", PoultryPiccata, Source.Item, BuffClassification.Nourishment, BuffImages.PoultryPiccata),
            new Buff("Dilled Poultry Piccata", DilledPoultryPiccata, Source.Item, BuffClassification.Nourishment, BuffImages.DilledPoultryPiccata),
            new Buff("Plate of Citrus Poultry with Almonds", PlaceOfCitrusPoultryWithAlmonds, Source.Item, BuffClassification.Nourishment, BuffImages.PlaceOfCitrusPoultryWithAlmonds),
            new Buff("Canned Tarragon Stuffed Poultry", CannedTarragonStuffedPoultry, Source.Item, BuffClassification.Nourishment, BuffImages.CannedTarragonStuffedPoultry),
            new Buff("Bowl of Salsa", BowlOfSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSalsa),
            new Buff("Bowl of Bean Salad", BowlOfBeanSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfBeanSalad),
            new Buff("Bowl of Avocado Salsa", BowlOfAvocadoSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfAvocadoSalsa),
            new Buff("Bowl of Chickpea Salad", BowlOfChickpeaSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfChickpeaSalad),
            new Buff("Bowl of Mango Salsa", BowlOfMangoSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfMangoSalsa),
            new Buff("Can of Mango Salsa", CanOfMangoSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.CanOfMangoSalsa),
            new Buff("Bloodstone Pot Pie", BloodstonePotPie, Source.Item, BuffClassification.Nourishment, BuffImages.BloodstonePotPie),
            new Buff("Poor Nourishment", PoorNourishment, Source.Item, BuffClassification.Nourishment, BuffImages.NourishmentFood),
            new Buff("Nourishment (Guild Banquet Table)", NourishmentGuildBanquetTable, Source.Item, BuffClassification.Nourishment, BuffImages.NourishmentBirthdayBlaster),
            new Buff("Weight of the World", WeightOfTheWorld, Source.Item, BuffClassification.Nourishment, BuffImages.NourishmentFood),
        };

        internal static readonly List<Buff> AscendedFood = new List<Buff>
        {
            // Ascended Food
            new Buff("Bowl of Fruit Salad with Cilantro Garnish", BowlOfFruitSaladWithCilantroGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFruitSaladWithCilantroGarnish),
            new Buff("Bowl of Fruit Salad with Mint Garnish", BowlOfFruitSaladWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFruitSaladWithMintGarnish),
            new Buff("Bowl of Fruit Salad with Orange-Clove Syrup", BowlOfFruitSaladWithOrangeCloveSyrup, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFruitSaladWithOrangeCloveSyrup),
            new Buff("Bowl of Sesame Fruit Salad", BowlOfSesameFruitSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSesameFruitSalad),
            new Buff("Bowl of Spiced Fruit Salad", BowlOfSpicedFruitSalad, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfSpicedFruitSalad),
            new Buff("Cilantro Lime Sous-Vide Steak", CilantroLimeSousVideSteak, Source.Item, BuffClassification.Nourishment, BuffImages.CilantroLimeSousVideSteak),
            new Buff("Cilantro and Cured Meat Flatbread", CilantroAndCuredMeatFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.CilantroAndCuredMeatFlatbread),
            new Buff("Clove and Veggie Flatbread", CloveAndVeggieFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.CloveAndVeggieFlatbread),
            new Buff("Clove-Spiced Creme Brulee", CloveSpicedCremeBrulee, Source.Item, BuffClassification.Nourishment, BuffImages.CloveSpicedCremeBrulee),
            new Buff("Clove-Spiced Eggs Benedict", CloveSpicedEggsBenedict, Source.Item, BuffClassification.Nourishment, BuffImages.CloveSpicedEggsBenedict),
            new Buff("Clove-Spiced Pear and Cured Meat Flatbread", CloveSpicedPearAndCuredMeatFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.CloveSpicedPearAndCuredMeatFlatbread),
            new Buff("Eggs Benedict with Mint-Parsley Sauce", EggsBenedictWithMintParsleySauce, Source.Item, BuffClassification.Nourishment, BuffImages.EggsBenedictWithMintParsleySauce),
            new Buff("Mango Cilantro Creme Brulee", MangoCilantroCremeBrulee, Source.Item, BuffClassification.Nourishment, BuffImages.MangoCilantroCremeBrulee),
            new Buff("Mint Creme Brulee", MintCremeBrulee, Source.Item, BuffClassification.Nourishment, BuffImages.MintCremeBrulee),
            new Buff("Mint Strawberry Cheesecake", MintStrawberryCheesecake, Source.Item, BuffClassification.Nourishment, BuffImages.MintStrawberryCheesecake),
            new Buff("Mint and Veggie Flatbread", MintAndVeggieFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.MintAndVeggieFlatbread),
            new Buff("Mint-Pear Cured Meat Flatbread", MintPearCuredMeatFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.MintPearCuredMeatFlatbread),
            new Buff("Mushroom Clove Sous-Vide Steak", MushroomCloveSousVideSteak, Source.Item, BuffClassification.Nourishment, BuffImages.MushroomCloveSousVideSteak),
            new Buff("Orange Clove Cheesecake", OrangeCloveCheesecake, Source.Item, BuffClassification.Nourishment, BuffImages.OrangeCloveCheesecake),
            new Buff("Peppercorn and Veggie Flatbread", PeppercornAndVeggieFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.PeppercornAndVeggieFlatbread),
            new Buff("Peppercorn-Crusted Sous-Vide Steak", PeppercornCrustedSousVideSteak, Source.Item, BuffClassification.Nourishment, BuffImages.PeppercornCrustedSousVideSteak),
            new Buff("Peppercorn-Spiced Eggs Benedict", PeppercornSpicedEggsBenedict, Source.Item, BuffClassification.Nourishment, BuffImages.PeppercornSpicedEggsBenedict),
            new Buff("Peppered Cured Meat Flatbread", PepperedCuredMeatFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.PepperedCuredMeatFlatbread),
            new Buff("Plate of Beef Carpaccio with Salsa Garnish", PlateOfBeefCarpaccioWithSalsaGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfBeefCarpaccioWithSalsaGarnish),
            new Buff("Plate of Beef Carpaccio with Mint Garnish", PlateOfBeefCarpaccioWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfBeefCarpaccioWithMintGarnish),
            new Buff("Plate of Clear Truffle and Cilantro Ravioli", PlateOfClearTruffleAndCilantroRavioli, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfClearTruffleAndCilantroRavioli),
            new Buff("Plate of Clear Truffle and Mint Ravioli", PlateOfClearTruffleAndMintRavioli, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfClearTruffleAndMintRavioli),
            new Buff("Plate of Clear Truffle and Sesame Ravioli", PlateOfClearTruffleAndSesameRavioli, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfClearTruffleAndSesameRavioli),
            new Buff("Plate of Clove-Spiced Beef Carpaccio", PlateOfCloveSpicedBeefCarpaccio, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCloveSpicedBeefCarpaccio),
            new Buff("Plate of Clove-Spiced Clear Truffle Ravioli", PlateOfCloveSpicedClearTruffleRavioli, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCloveSpicedClearTruffleRavioli),
            new Buff("Plate of Clove-Spiced Coq Au Vin", PlateOfCloveSpicedCoqAuVin, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCloveSpicedCoqAuVin),
            new Buff("Plate of Clove-Spiced Poultry Aspic", PlateOfCloveSpicedPoultryAspic, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCloveSpicedPoultryAspic),
            new Buff("Plate of Coq Au Vin with Mint Garnish", PlateOfCoqAuVinWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCoqAuVinWithMintGarnish),
            new Buff("Plate of Coq Au Vin with Salsa", PlateOfCoqAuVinWithSalsa, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCoqAuVinWithSalsa),
            new Buff("Plate of Peppercorn-Spiced Beef Carpaccio", PlateOfPeppercornSpicedBeefCarpaccio, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPeppercornSpicedBeefCarpaccio),
            new Buff("Plate of Peppercorn-Spiced Coq Au Vin", PlateOfPeppercornSpicedCoqAuVin, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPeppercornSpicedCoqAuVin),
            new Buff("Plate of Peppercorn-Spiced Poultry Aspic", PlateOfPeppercornSpicedPoultryAspic, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPeppercornSpicedPoultryAspic),
            new Buff("Plate of Peppered Clear Truffle Ravioli", PlateOfPepperedClearTruffleRavioli, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPepperedClearTruffleRavioli),
            new Buff("Plate of Poultry Aspic with Mint Garnish", PlateOfPoultryAspicWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPoultryAspicWithMintGarnish),
            new Buff("Plate of Poultry Aspic with Salsa Garnish", PlateOfPoultryAspicWithSalsaGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfPoultryAspicWithSalsaGarnish),
            new Buff("Plate of Sesame Poultry Aspic", PlateOfSesamePoultryAspic, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSesamePoultryAspic),
            new Buff("Plate of Sesame-Crusted Coq Au Vin", PlateOfSesameCrustedCoqAuVin, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSesameCrustedCoqAuVin),
            new Buff("Plate of Sesame-Ginger Beef Carpaccio", PlateOfSesameGingerBeefCarpaccio, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfSesameGingerBeefCarpaccio),
            new Buff("Salsa Eggs Benedict", SalsaEggsBenedict, Source.Item, BuffClassification.Nourishment, BuffImages.SalsaEggsBenedict),
            new Buff("Salsa-Topped Veggie Flatbread", SalsaToppedVeggieFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.SalsaToppedVeggieFlatbread),
            new Buff("Sesame Cheesecake", SesameCheesecake, Source.Item, BuffClassification.Nourishment, BuffImages.SesameCheesecake),
            new Buff("Sesame Creme Brulee", SesameCremeBrulee, Source.Item, BuffClassification.Nourishment, BuffImages.SesameCremeBrulee),
            new Buff("Sesame Eggs Benedict", SesameEggsBenedict, Source.Item, BuffClassification.Nourishment, BuffImages.SesameEggsBenedict),
            new Buff("Sesame Veggie Flatbread", SesameVeggieFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.SesameVeggieFlatbread),
            new Buff("Sesame-Asparagus and Cured Meat Flatbread", SesameAsparagusAndCuredMeatFlatbread, Source.Item, BuffClassification.Nourishment, BuffImages.SesameAsparagusAndCuredMeatFlatbread),
            new Buff("Sous-Vide Steak with Mint-Parsley Sauce", SousVideSteakWithMintParsleySauce, Source.Item, BuffClassification.Nourishment, BuffImages.SousVideSteakWithMintParsleySauce),
            new Buff("Soy-Sesame Sous-Vide Steak", SoySesameSousVideSteak, Source.Item, BuffClassification.Nourishment, BuffImages.SoySesameSousVideSteak),
            new Buff("Spherified Cilantro Oyster Soup", SpherifiedCilantroOysterSoup, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedCilantroOysterSoup),
            new Buff("Spherified Clove-Spiced Oyster Soup", SpherifiedCloveSpicedOysterSoup, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedCloveSpicedOysterSoup),
            new Buff("Spherified Oyster Soup with Mint Garnish", SpherifiedOysterSoupWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedOysterSoupWithMintGarnish),
            new Buff("Spherified Peppercorn-Spiced Oyster Soup", SpherifiedPeppercornSpicedOysterSoup, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedPeppercornSpicedOysterSoup),
            new Buff("Spherified Sesame Oyster Soup", SpherifiedSesameOysterSoup, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedSesameOysterSoup),
            new Buff("Spiced Pepper Creme Brulee", SpicedPepperCremeBrulee, Source.Item, BuffClassification.Nourishment, BuffImages.SpicedPepperCremeBrulee),
            new Buff("Spiced Peppercorn Cheesecake", SpicedPeppercornCheesecake, Source.Item, BuffClassification.Nourishment, BuffImages.SpicedPeppercornCheesecake),
            new Buff("Strawberry Cilantro Cheesecake", StrawberryCilantroCheesecake, Source.Item, BuffClassification.Nourishment, BuffImages.StrawberryCilantroCheesecake),
            new Buff("Plate of Imperial Palace Special", PlateOfImperialPalaceSpecial, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfImperialPalaceSpecial),
            new Buff("Plate of Crispy Fish Pancakes", PlateOfCrispyFishPancakes, Source.Item, BuffClassification.Nourishment, BuffImages.PlateOfCrispyFishPancakes),
            new Buff("Bowl of Jade Sea Bounty", BowlOfJadeSeaBounty, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfJadeSeaBounty),
            new Buff("Bowl of Echovald Hotpot", BowlOfEchovaldHotpot, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfEchovaldHotpot),
            new Buff("Flight Of Sushi", FlightOfSushi, Source.Item, BuffClassification.Nourishment, BuffImages.FlightOfSushi),
            new Buff("Bowl of Mists-Infused Fruit Salad with Mint Garnish", BowlOfMistsInfusedFruitSaladWithMintGarnish, Source.Item, BuffClassification.Nourishment, BuffImages.BowlOfFruitSaladWithMintGarnish),
            new Buff("Mists-Infused Peppercorn-Crusted Sous-Vide Steak", MistsInfusedPeppercornCrustedSousVideSteak, Source.Item, BuffClassification.Nourishment, BuffImages.PeppercornCrustedSousVideSteak),
            new Buff("Mists-Infused Spherified Peppercorn-Spiced Oyster Soup", MistsInfusedSpherifiedPeppercornSpicedOysterSoup, Source.Item, BuffClassification.Nourishment, BuffImages.SpherifiedPeppercornSpicedOysterSoup),
        };

        internal static readonly List<Buff> FoodProcs = new List<Buff>
        {
            // Buff procs for On Kill Food
            new Buff("Nourishment (Bonus 40 Power)", NourishmentBonusPower40, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 60 Power)", NourishmentBonusPower60, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 100 Power)", NourishmentBonusPower100, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 120 Power)", NourishmentBonusPower120, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 160 Power)", NourishmentBonusPower160, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 200 Power)", NourishmentBonusPower200, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 100 Power & 100 Ferocity)", NourishmentBonusPowerFerocity100, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Nourishment (Bonus 150 Power & 150 Vitality)", NourishmentBonusPowerVitality150, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
            new Buff("Malice (Bonus Condition Damage)", MaliceBonusConditionDamage, Source.Item, BuffClassification.Offensive, BuffImages.ChampionOfTheCrown),
        };

    }
}
